import 'dart:typed_data';
import 'dart:convert';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:intl/intl.dart';
import 'package:flutter/foundation.dart';
import 'package:http/http.dart' as http;

// Conditional imports for different platforms
import 'pdf_export_io.dart' if (dart.library.html) 'pdf_export_web.dart';

class PdfExportService {
  static Future<dynamic> exportTransactionsToPdf({
    required List<Map<String, dynamic>> transactions,
    required String reportTitle,
    required String fileName,
    Map<String, dynamic>? businessInfo,
  }) async {
    // Use provided business info or fallback for consistency
    Map<String, dynamic> businessData = businessInfo ?? {
      'name': 'XXX',
      'tagline': 'XXX',
      'contact_email': 'XXX',
      'contact_phone': 'XXX',
      'address': 'XXX',
      'primary_color': '#1976D2',
    };
    
    if (businessInfo != null) {
      print('🔍 PDF: Using real business branding: ${businessInfo['name']}');
      print('🔍 PDF: Business info full data: $businessInfo');
    } else {
      print('🔍 PDF: Using fallback business branding for consistency');
    }
    
    // Pre-load business logo if available
    await _preloadBusinessLogo(businessData);
    
    // Create PDF document
    final pdf = pw.Document();
    
    // Calculate how many rows can fit per page - optimized for maximum data
    const int rowsPerPage = 35; // Maximized for compact layout
    const int headerHeight = 120; // Reduced header height
    const int summaryHeight = 80; // Reduced summary height
    const int pageHeight = 800; // Approximate available height per page
    
    if (transactions.isEmpty) {
      // Single page for empty state
      pdf.addPage(
        pw.Page(
          pageFormat: PdfPageFormat.a4,
          build: (pw.Context context) {
            return pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                _buildCompactHeader(businessData, reportTitle),
                pw.SizedBox(height: 15),
                _buildCompactInvoiceDetails(businessData, reportTitle: reportTitle),
                pw.SizedBox(height: 15),
                _buildEmptyState(),
                
                // Footer with page number and company info
                pw.SizedBox(height: 10), // Reduced spacing
                pw.Container(
                  width: double.infinity,
                  padding: const pw.EdgeInsets.symmetric(vertical: 8),
                  decoration: pw.BoxDecoration(
                    border: pw.Border(
                      top: pw.BorderSide(color: PdfColors.grey300, width: 0.5),
                    ),
                  ),
                  child: pw.Column(
                    children: [
                      pw.Text(
                        'Page 1 of 1',
                        style: const pw.TextStyle(
                          fontSize: 9,
                          color: PdfColors.grey600,
                        ),
                        textAlign: pw.TextAlign.center,
                      ),
                      pw.SizedBox(height: 4),
                      pw.Text(
                        'Generated by Kismayo ICT Solution | Phone: 0614112537 | Website: kismayoict.com',
                        style: const pw.TextStyle(
                          fontSize: 8,
                          color: PdfColors.grey500,
                        ),
                        textAlign: pw.TextAlign.center,
                      ),
                    ],
                  ),
                ),
              ],
            );
          },
        ),
      );
    } else {
      // Calculate total pages needed
      final int totalPages = ((transactions.length / rowsPerPage).ceil()).clamp(1, 999);
      print('🔍 PDF: Creating $totalPages pages for ${transactions.length} transactions');
      print('🔍 PDF: Rows per page: $rowsPerPage');
      print('🔍 PDF: Total transactions: ${transactions.length}');
      
      for (int pageIndex = 0; pageIndex < totalPages; pageIndex++) {
        final int startIndex = pageIndex * rowsPerPage;
        final int endIndex = (startIndex + rowsPerPage).clamp(0, transactions.length);
        final List<Map<String, dynamic>> pageTransactions = transactions.sublist(startIndex, endIndex);
        
        print('🔍 PDF: Creating page ${pageIndex + 1} with ${pageTransactions.length} transactions (${startIndex + 1}-${endIndex})');
        
        pdf.addPage(
          pw.Page(
            pageFormat: PdfPageFormat.a4,
            build: (pw.Context context) {
              return pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  // Header (only on first page)
                  if (pageIndex == 0) ...[
                    _buildCompactHeader(businessData, reportTitle),
                    pw.SizedBox(height: 8), // Reduced spacing
                    _buildCompactInvoiceDetails(businessData, reportTitle: reportTitle),
                    pw.SizedBox(height: 8), // Reduced spacing
                  ],
                  
                  // Page number indicator
                  if (pageIndex > 0) ...[
                    pw.Container(
                      width: double.infinity,
                      padding: const pw.EdgeInsets.all(4), // Reduced padding
                      decoration: pw.BoxDecoration(
                        color: PdfColors.grey100,
                        borderRadius: const pw.BorderRadius.all(pw.Radius.circular(4)),
                      ),
                      child: pw.Text(
                        'Page ${pageIndex + 1} of $totalPages',
                        style: const pw.TextStyle(
                          fontSize: 8, // Reduced font size
                          fontWeight: pw.FontWeight.bold,
                          color: PdfColors.grey700,
                        ),
                        textAlign: pw.TextAlign.center,
                      ),
                    ),
                    pw.SizedBox(height: 6), // Reduced spacing
                  ],
                  
                  // Transactions Table for this page
                  _buildCompactInvoiceTable(pageTransactions, showTotals: pageIndex == totalPages - 1, allTransactions: transactions),
                  
                  // Summary (only on last page)
                  if (pageIndex == totalPages - 1) ...[
                    pw.SizedBox(height: 8), // Reduced spacing
                    _buildCompactInvoiceSummary(transactions),
                  ],
                  
                  // Footer with page number and company info
                  pw.SizedBox(height: 10), // Reduced spacing
                  pw.Container(
                    width: double.infinity,
                    padding: const pw.EdgeInsets.symmetric(vertical: 8),
                    decoration: pw.BoxDecoration(
                      border: pw.Border(
                        top: pw.BorderSide(color: PdfColors.grey300, width: 0.5),
                      ),
                    ),
                    child: pw.Column(
                      children: [
                        pw.Text(
                          'Page ${pageIndex + 1} of $totalPages',
                          style: const pw.TextStyle(
                            fontSize: 9,
                            color: PdfColors.grey600,
                          ),
                          textAlign: pw.TextAlign.center,
                        ),
                        pw.SizedBox(height: 4),
                        pw.Text(
                          'Generated by Kismayo ICT Solution | Phone: 0614112537 | Website: kismayoict.com',
                          style: const pw.TextStyle(
                            fontSize: 8,
                            color: PdfColors.grey500,
                          ),
                          textAlign: pw.TextAlign.center,
                        ),
                      ],
                    ),
                  ),
                ],
              );
            },
          ),
        );
      }
    }
    
    // Save PDF using platform-specific implementation
    final pdfBytes = await pdf.save();
    return await PdfExportPlatform.savePdf(pdfBytes, fileName);
  }

  static Future<dynamic> exportStockSummaryToPdf({
    required List<Map<String, dynamic>> stockData,
    required String reportTitle,
    required String fileName,
    Map<String, dynamic>? businessInfo,
  }) async {
    // Use provided business info or fallback for consistency
    Map<String, dynamic> businessData = businessInfo ?? {
      'name': 'XXX',
      'tagline': 'XXX',
      'contact_email': 'XXX',
      'contact_phone': 'XXX',
      'address': 'XXX',
      'primary_color': '#1976D2',
    };
    
    if (businessInfo != null) {
      print('🔍 PDF: Using real business branding: ${businessInfo['name']}');
      print('🔍 PDF Stock Summary: Business info full data: $businessInfo');
    } else {
      print('🔍 PDF: Using fallback business branding for stock summary');
    }
    
    // Pre-load business logo if available
    await _preloadBusinessLogo(businessData);
    
    // Create PDF document
    final pdf = pw.Document();
    
    // Calculate how many rows can fit per page - optimized for maximum data
    const int rowsPerPage = 25; // Maximized for compact layout - Stock summary rows are larger
    const int headerHeight = 120; // Reduced header height
    const int summaryHeight = 80; // Reduced summary height
    const int pageHeight = 800; // Approximate available height per page
    
    if (stockData.isEmpty) {
      // Single page for empty state
      pdf.addPage(
        pw.Page(
          pageFormat: PdfPageFormat.a4,
          build: (pw.Context context) {
            return pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                _buildCompactHeader(businessData, reportTitle),
                pw.SizedBox(height: 15),
                _buildCompactInvoiceDetails(businessData, reportTitle: reportTitle),
                pw.SizedBox(height: 15),
                _buildEmptyState(),
                
                // Footer with page number and company info
                pw.SizedBox(height: 10), // Reduced spacing
                pw.Container(
                  width: double.infinity,
                  padding: const pw.EdgeInsets.symmetric(vertical: 8),
                  decoration: pw.BoxDecoration(
                    border: pw.Border(
                      top: pw.BorderSide(color: PdfColors.grey300, width: 0.5),
                    ),
                  ),
                  child: pw.Column(
                    children: [
                      pw.Text(
                        'Page 1 of 1',
                        style: const pw.TextStyle(
                          fontSize: 9,
                          color: PdfColors.grey600,
                        ),
                        textAlign: pw.TextAlign.center,
                      ),
                      pw.SizedBox(height: 4),
                      pw.Text(
                        'Generated by Kismayo ICT Solution | Phone: 0614112537 | Website: kismayoict.com',
                        style: const pw.TextStyle(
                          fontSize: 8,
                          color: PdfColors.grey500,
                        ),
                        textAlign: pw.TextAlign.center,
                      ),
                    ],
                  ),
                ),
              ],
            );
          },
        ),
      );
    } else {
      // Calculate total pages needed
      final int totalPages = ((stockData.length / rowsPerPage).ceil()).clamp(1, 999);
      print('🔍 PDF Stock Summary: Creating $totalPages pages for ${stockData.length} products');
      print('🔍 PDF Stock Summary: Rows per page: $rowsPerPage');
      print('🔍 PDF Stock Summary: Total products: ${stockData.length}');
      
      for (int pageIndex = 0; pageIndex < totalPages; pageIndex++) {
        final int startIndex = pageIndex * rowsPerPage;
        final int endIndex = (startIndex + rowsPerPage).clamp(0, stockData.length);
        final List<Map<String, dynamic>> pageStockData = stockData.sublist(startIndex, endIndex);
        
        print('🔍 PDF Stock Summary: Creating page ${pageIndex + 1} with ${pageStockData.length} products (${startIndex + 1}-${endIndex})');
        
        pdf.addPage(
          pw.Page(
            pageFormat: PdfPageFormat.a4,
            build: (pw.Context context) {
              return pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  // Header (only on first page)
                  if (pageIndex == 0) ...[
                    _buildCompactHeader(businessData, reportTitle),
                    pw.SizedBox(height: 8), // Reduced spacing
                    _buildCompactInvoiceDetails(businessData, reportTitle: reportTitle),
                    pw.SizedBox(height: 8), // Reduced spacing
                  ],
                  
                  // Page number indicator
                  if (pageIndex > 0) ...[
                    pw.Container(
                      width: double.infinity,
                      padding: const pw.EdgeInsets.all(4), // Reduced padding
                      decoration: pw.BoxDecoration(
                        color: PdfColors.grey100,
                        borderRadius: const pw.BorderRadius.all(pw.Radius.circular(4)),
                      ),
                      child: pw.Text(
                        'Page ${pageIndex + 1} of $totalPages',
                        style: const pw.TextStyle(
                          fontSize: 8, // Reduced font size
                          fontWeight: pw.FontWeight.bold,
                          color: PdfColors.grey700,
                        ),
                        textAlign: pw.TextAlign.center,
                      ),
                    ),
                    pw.SizedBox(height: 6), // Reduced spacing
                  ],
                  
                  // Stock Summary Table for this page
                  _buildStockSummaryTable(pageStockData, showTotals: pageIndex == totalPages - 1, allStockData: stockData),
                  
                  // Summary (only on last page)
                  if (pageIndex == totalPages - 1) ...[
                    pw.SizedBox(height: 8), // Reduced spacing
                    _buildStockSummarySummary(stockData),
                  ],
                  
                  // Footer with page number and company info
                  pw.SizedBox(height: 10), // Reduced spacing
                  pw.Container(
                    width: double.infinity,
                    padding: const pw.EdgeInsets.symmetric(vertical: 8),
                    decoration: pw.BoxDecoration(
                      border: pw.Border(
                        top: pw.BorderSide(color: PdfColors.grey300, width: 0.5),
                      ),
                    ),
                    child: pw.Column(
                      children: [
                        pw.Text(
                          'Page ${pageIndex + 1} of $totalPages',
                          style: const pw.TextStyle(
                            fontSize: 9,
                            color: PdfColors.grey600,
                          ),
                          textAlign: pw.TextAlign.center,
                        ),
                        pw.SizedBox(height: 4),
                        pw.Text(
                          'Generated by Kismayo ICT Solution | Phone: 0614112537 | Website: kismayoict.com',
                          style: const pw.TextStyle(
                            fontSize: 8,
                            color: PdfColors.grey500,
                          ),
                          textAlign: pw.TextAlign.center,
                        ),
                      ],
                    ),
                  ),
                ],
              );
            },
          ),
        );
      }
    }
    
    // Save PDF using platform-specific implementation
    final pdfBytes = await pdf.save();
    return await PdfExportPlatform.savePdf(pdfBytes, fileName);
  }
  

  
    // Build compact header
  static pw.Widget _buildCompactHeader(Map<String, dynamic> businessInfo, String reportTitle) {
    final businessName = businessInfo['name'] ?? 'XXX';
    final primaryColor = _parseColor(businessInfo['primary_color'] ?? '#1976D2');
    final tagline = businessInfo['tagline'] ?? 'XXX';
    
    print('🔍 PDF Header: Business name: "$businessName"');
    print('🔍 PDF Header: Business tagline: "$tagline"');
    print('🔍 PDF Header: Report title: "$reportTitle"');
    
    return pw.Container(
      width: double.infinity,
      padding: const pw.EdgeInsets.all(8), // Reduced padding
      decoration: pw.BoxDecoration(
        color: primaryColor,
        borderRadius: const pw.BorderRadius.all(pw.Radius.circular(4)), // Smaller radius
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          // Top Row: Business Info and Logo
          pw.Row(
            children: [
              // Business Logo
              _buildBusinessLogo(businessInfo, primaryColor),
              
              pw.SizedBox(width: 8), // Reduced spacing
              
              // Business Info
              pw.Expanded(
                child: pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text(
                      businessName,
                      style: pw.TextStyle(
                        color: PdfColors.white,
                        fontSize: 14, // Reduced font size
                        fontWeight: pw.FontWeight.bold,
                      ),
                      maxLines: 1, // Single line to save space
                    ),
                    pw.Text(
                      tagline,
                      style: pw.TextStyle(
                        color: PdfColors.grey300,
                        fontSize: 9, // Reduced font size
                        fontWeight: pw.FontWeight.normal,
                      ),
                    ),
                  ],
                ),
              ),
            ],
          ),
          
          pw.SizedBox(height: 6), // Reduced spacing
          
          // Bottom Row: Report Title
          pw.Container(
            width: double.infinity,
            padding: const pw.EdgeInsets.symmetric(horizontal: 8, vertical: 4), // Reduced padding
            child: pw.Text(
              reportTitle,
              style: pw.TextStyle(
                color: PdfColors.white,
                fontSize: 9, // Reduced font size
                fontWeight: pw.FontWeight.bold,
              ),
              textAlign: pw.TextAlign.center,
            ),
          ),
        ],
      ),
    );
  }
  
  // Build compact invoice details
  static pw.Widget _buildCompactInvoiceDetails(Map<String, dynamic> businessInfo, {String? reportTitle}) {
    final contactEmail = businessInfo['contact_email'] ?? 'XXX';
    final contactPhone = businessInfo['contact_phone'] ?? 'XXX';
    final address = businessInfo['address'] ?? 'XXX';
    
    // Extract filter information from report title
    String filterInfo = 'No filters applied';
    if (reportTitle != null) {
      if (reportTitle.contains('(') && reportTitle.contains(')')) {
        // Extract filter info from parentheses
        final startIndex = reportTitle.indexOf('(');
        final endIndex = reportTitle.indexOf(')');
        if (startIndex != -1 && endIndex != -1 && endIndex > startIndex) {
          filterInfo = reportTitle.substring(startIndex + 1, endIndex);
        }
      } else {
        // If no parentheses, show the full title as filter info
        filterInfo = reportTitle;
      }
    }
    
    return pw.Container(
      padding: const pw.EdgeInsets.all(6), // Reduced padding
      decoration: pw.BoxDecoration(
        color: PdfColors.grey50,
        borderRadius: const pw.BorderRadius.all(pw.Radius.circular(4)), // Smaller radius
        border: pw.Border.all(color: PdfColors.grey300),
      ),
      child: pw.Row(
        children: [
          // Contact Information
          pw.Expanded(
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(
                  'Contact Info',
                  style: pw.TextStyle(
                    fontSize: 9, // Reduced font size
                    fontWeight: pw.FontWeight.bold,
                    color: PdfColors.grey800,
                  ),
                ),
                pw.SizedBox(height: 2), // Reduced spacing
                pw.Text('Email: $contactEmail', style: const pw.TextStyle(fontSize: 7)), // Smaller font
                pw.Text('Phone: $contactPhone', style: const pw.TextStyle(fontSize: 7)), // Smaller font
              ],
            ),
          ),
          
          // Address
          pw.Expanded(
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(
                  'Address',
                  style: pw.TextStyle(
                    fontSize: 9, // Reduced font size
                    fontWeight: pw.FontWeight.bold,
                    color: PdfColors.grey800,
                  ),
                ),
                pw.SizedBox(height: 2), // Reduced spacing
                pw.Text(
                  address,
                  style: const pw.TextStyle(fontSize: 7), // Smaller font
                  maxLines: 1, // Single line to save space
                ),
              ],
            ),
          ),
          
          // Invoice Details
          pw.Expanded(
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.end,
              children: [
                pw.Text(
                  'Report Details',
                  style: pw.TextStyle(
                    fontSize: 9, // Reduced font size
                    fontWeight: pw.FontWeight.bold,
                    color: PdfColors.grey800,
                  ),
                ),
                pw.SizedBox(height: 2), // Reduced spacing
                pw.Text(
                  'Date: ${DateFormat('MMM dd, yyyy').format(DateTime.now())}',
                  style: const pw.TextStyle(fontSize: 7), // Smaller font
                ),
                pw.Text(
                  'Time: ${DateFormat('HH:mm').format(DateTime.now())}',
                  style: const pw.TextStyle(fontSize: 7), // Smaller font
                ),
                pw.SizedBox(height: 1), // Reduced spacing
                pw.Text(
                  'Filters: $filterInfo',
                  style: const pw.TextStyle(fontSize: 7), // Smaller font
                  textAlign: pw.TextAlign.right,
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
  
  // Build stock summary table
  static pw.Widget _buildStockSummaryTable(List<Map<String, dynamic>> stockData, {
    bool showTotals = true,
    List<Map<String, dynamic>>? allStockData,
  }) {
    // Calculate column totals from ALL data if provided, otherwise from current page data
    final dataForTotals = allStockData ?? stockData;
    final totalSold = dataForTotals.fold(0, (sum, row) => sum + _safeToInt(row['quantity_sold']));
    final totalRemaining = dataForTotals.fold(0, (sum, row) => sum + _safeToInt(row['quantity_remaining']));
    final totalRevenue = dataForTotals.fold(0.0, (sum, row) => sum + _safeToDouble(row['revenue']));
    final totalProfit = dataForTotals.fold(0.0, (sum, row) => sum + _safeToDouble(row['profit']));
    final totalProducts = dataForTotals.length;
    
    return pw.Container(
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.grey400),
        borderRadius: const pw.BorderRadius.all(pw.Radius.circular(6)),
      ),
      child: pw.Table(
        border: pw.TableBorder.all(color: PdfColors.grey400, width: 0.3),
        columnWidths: const {
          0: pw.FlexColumnWidth(2), // Product
          1: pw.FlexColumnWidth(1), // SKU
          2: pw.FlexColumnWidth(1), // Category
          3: pw.FlexColumnWidth(0.8), // Sold Qty
          4: pw.FlexColumnWidth(0.8), // Qty Remaining
          5: pw.FlexColumnWidth(1), // Revenue
          6: pw.FlexColumnWidth(1), // Profit
        },
        children: [
          // Table Header
          pw.TableRow(
            decoration: const pw.BoxDecoration(color: PdfColors.grey200),
            children: [
              pw.Padding(
                padding: const pw.EdgeInsets.all(3), // Reduced padding
                child: pw.Text(
                  'Product',
                  style: pw.TextStyle(
                    fontWeight: pw.FontWeight.bold,
                    fontSize: 8, // Reduced font size
                  ),
                ),
              ),
              pw.Padding(
                padding: const pw.EdgeInsets.all(3), // Reduced padding
                child: pw.Text(
                  'SKU',
                  style: pw.TextStyle(
                    fontWeight: pw.FontWeight.bold,
                    fontSize: 8, // Reduced font size
                  ),
                  textAlign: pw.TextAlign.center,
                ),
              ),
              pw.Padding(
                padding: const pw.EdgeInsets.all(3), // Reduced padding
                child: pw.Text(
                  'Category',
                  style: pw.TextStyle(
                    fontWeight: pw.FontWeight.bold,
                    fontSize: 8, // Reduced font size
                  ),
                ),
              ),
              pw.Padding(
                padding: const pw.EdgeInsets.all(3), // Reduced padding
                child: pw.Text(
                  'Sold',
                  style: pw.TextStyle(
                    fontWeight: pw.FontWeight.bold,
                    fontSize: 8, // Reduced font size
                  ),
                  textAlign: pw.TextAlign.center,
                ),
              ),
              pw.Padding(
                padding: const pw.EdgeInsets.all(3), // Reduced padding
                child: pw.Text(
                  'Remaining',
                  style: pw.TextStyle(
                    fontWeight: pw.FontWeight.bold,
                    fontSize: 8, // Reduced font size
                  ),
                  textAlign: pw.TextAlign.center,
                ),
              ),
              pw.Padding(
                padding: const pw.EdgeInsets.all(3), // Reduced padding
                child: pw.Text(
                  'Revenue',
                  style: pw.TextStyle(
                    fontWeight: pw.FontWeight.bold,
                    fontSize: 8, // Reduced font size
                  ),
                  textAlign: pw.TextAlign.center,
                ),
              ),
              pw.Padding(
                padding: const pw.EdgeInsets.all(3), // Reduced padding
                child: pw.Text(
                  'Profit',
                  style: pw.TextStyle(
                    fontWeight: pw.FontWeight.bold,
                    fontSize: 8, // Reduced font size
                  ),
                  textAlign: pw.TextAlign.center,
                ),
              ),
            ],
          ),
          
          // Table Rows
          ...stockData.map((row) => pw.TableRow(
            children: [
              pw.Padding(
                padding: const pw.EdgeInsets.all(2), // Reduced padding
                child: pw.Text(
                  row['product_name'] ?? '',
                  style: const pw.TextStyle(fontSize: 7), // Smaller font
                  maxLines: 1, // Single line to save space
                ),
              ),
              pw.Padding(
                padding: const pw.EdgeInsets.all(2), // Reduced padding
                child: pw.Text(
                  row['sku'] ?? '',
                  style: const pw.TextStyle(fontSize: 7), // Smaller font
                  textAlign: pw.TextAlign.center,
                ),
              ),
              pw.Padding(
                padding: const pw.EdgeInsets.all(2), // Reduced padding
                child: pw.Text(
                  row['category_name'] ?? '',
                  style: const pw.TextStyle(fontSize: 7), // Smaller font
                ),
              ),
              pw.Padding(
                padding: const pw.EdgeInsets.all(2), // Reduced padding
                child: pw.Text(
                  _safeToInt(row['quantity_sold']).toString(),
                  style: const pw.TextStyle(fontSize: 7), // Smaller font
                  textAlign: pw.TextAlign.center,
                ),
              ),
              pw.Padding(
                padding: const pw.EdgeInsets.all(2), // Reduced padding
                child: pw.Text(
                  _safeToInt(row['quantity_remaining']).toString(),
                  style: const pw.TextStyle(fontSize: 7), // Smaller font
                  textAlign: pw.TextAlign.center,
                ),
              ),
              pw.Padding(
                padding: const pw.EdgeInsets.all(2), // Reduced padding
                child: pw.Text(
                  '\$${_safeToDouble(row['revenue']).toStringAsFixed(2)}',
                  style: const pw.TextStyle(fontSize: 7), // Smaller font
                  textAlign: pw.TextAlign.center,
                ),
              ),
              pw.Padding(
                padding: const pw.EdgeInsets.all(2), // Reduced padding
                child: pw.Text(
                  '\$${_safeToDouble(row['profit']).toStringAsFixed(2)}',
                  style: const pw.TextStyle(fontSize: 7), // Smaller font
                  textAlign: pw.TextAlign.center,
                ),
              ),
            ],
          )).toList(),
          
          // Column Totals Row - Only show on last page
          if (showTotals) pw.TableRow(
            decoration: const pw.BoxDecoration(color: PdfColors.grey100),
            children: [
              pw.Padding(
                padding: const pw.EdgeInsets.all(4),
                child: pw.Text(
                  'TOTALS:',
                  style: pw.TextStyle(
                    fontSize: 8,
                    fontWeight: pw.FontWeight.bold,
                    color: PdfColors.grey800,
                  ),
                  textAlign: pw.TextAlign.center,
                ),
              ),
              pw.Padding(
                padding: const pw.EdgeInsets.all(4),
                child: pw.Text(
                  totalProducts.toString(),
                  style: pw.TextStyle(
                    fontSize: 8,
                    fontWeight: pw.FontWeight.bold,
                    color: PdfColors.grey800,
                  ),
                  textAlign: pw.TextAlign.center,
                ),
              ),
              pw.Padding(
                padding: const pw.EdgeInsets.all(4),
                child: pw.Text(
                  '', // Empty for category column
                  style: const pw.TextStyle(fontSize: 7),
                ),
              ),
              pw.Padding(
                padding: const pw.EdgeInsets.all(4),
                child: pw.Text(
                  totalSold.toString(),
                  style: pw.TextStyle(
                    fontSize: 8,
                    fontWeight: pw.FontWeight.bold,
                    color: PdfColors.grey800,
                  ),
                  textAlign: pw.TextAlign.center,
                ),
              ),
              pw.Padding(
                padding: const pw.EdgeInsets.all(4),
                child: pw.Text(
                  totalRemaining.toString(),
                  style: pw.TextStyle(
                    fontSize: 8,
                    fontWeight: pw.FontWeight.bold,
                    color: PdfColors.grey800,
                  ),
                  textAlign: pw.TextAlign.center,
                ),
              ),
              pw.Padding(
                padding: const pw.EdgeInsets.all(4),
                child: pw.Text(
                  '\$${totalRevenue.toStringAsFixed(2)}',
                  style: pw.TextStyle(
                    fontSize: 8,
                    fontWeight: pw.FontWeight.bold,
                    color: PdfColors.grey800,
                  ),
                  textAlign: pw.TextAlign.center,
                ),
              ),
              pw.Padding(
                padding: const pw.EdgeInsets.all(4),
                child: pw.Text(
                  '\$${totalProfit.toStringAsFixed(2)}',
                  style: pw.TextStyle(
                    fontSize: 9,
                    fontWeight: pw.FontWeight.bold,
                    color: PdfColors.grey900,
                  ),
                  textAlign: pw.TextAlign.center,
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }

  // Build compact invoice table
  static pw.Widget _buildCompactInvoiceTable(List<Map<String, dynamic>> transactions, {
    bool showTotals = true,
    List<Map<String, dynamic>>? allTransactions,
  }) {
    // Calculate column totals from ALL data if provided, otherwise from current page data
    final dataForTotals = allTransactions ?? transactions;
    final totalCost = dataForTotals.fold(0.0, (sum, tx) {
      final quantity = _safeToInt(tx['quantity']);
      final costPrice = _getCostPrice(tx);
      return sum + (quantity * costPrice);
    });
    
    // Price column doesn't need a total - it shows unit prices
    
    final totalQuantity = dataForTotals.fold(0, (sum, tx) => sum + _safeToInt(tx['quantity']));
    final grandTotal = dataForTotals.fold(0.0, (sum, tx) => sum + _calculateRowTotal(tx));
    
    return pw.Container(
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.grey400),
        borderRadius: const pw.BorderRadius.all(pw.Radius.circular(6)),
      ),
      child: pw.Table(
        border: pw.TableBorder.all(color: PdfColors.grey400, width: 0.3),
        columnWidths: const {
          0: pw.FlexColumnWidth(1), // Date
          1: pw.FlexColumnWidth(2.5), // Product
          2: pw.FlexColumnWidth(0.6), // Qty
          3: pw.FlexColumnWidth(1), // Cost Price
          4: pw.FlexColumnWidth(1), // Sale Price
          5: pw.FlexColumnWidth(1.2), // Total
        },
        children: [
          // Table Header
          pw.TableRow(
            decoration: const pw.BoxDecoration(color: PdfColors.grey200),
            children: [
              pw.Padding(
                padding: const pw.EdgeInsets.all(3), // Reduced padding
                child: pw.Text(
                  'Date',
                  style: pw.TextStyle(
                    fontWeight: pw.FontWeight.bold,
                    fontSize: 8, // Reduced font size
                  ),
                  textAlign: pw.TextAlign.center,
                ),
              ),
              pw.Padding(
                padding: const pw.EdgeInsets.all(3), // Reduced padding
                child: pw.Text(
                  'Product',
                  style: pw.TextStyle(
                    fontWeight: pw.FontWeight.bold,
                    fontSize: 8, // Reduced font size
                  ),
                ),
              ),
              pw.Padding(
                padding: const pw.EdgeInsets.all(3), // Reduced padding
                child: pw.Text(
                  'Qty',
                  style: pw.TextStyle(
                    fontWeight: pw.FontWeight.bold,
                    fontSize: 8, // Reduced font size
                  ),
                  textAlign: pw.TextAlign.center,
                ),
              ),
              pw.Padding(
                padding: const pw.EdgeInsets.all(3), // Reduced padding
                child: pw.Text(
                  'Cost',
                  style: pw.TextStyle(
                    fontWeight: pw.FontWeight.bold,
                    fontSize: 8, // Reduced font size
                  ),
                  textAlign: pw.TextAlign.center,
                ),
              ),
              pw.Padding(
                padding: const pw.EdgeInsets.all(3), // Reduced padding
                child: pw.Text(
                  'Price',
                  style: pw.TextStyle(
                    fontWeight: pw.FontWeight.bold,
                    fontSize: 8, // Reduced font size
                  ),
                  textAlign: pw.TextAlign.center,
                ),
              ),
              pw.Padding(
                padding: const pw.EdgeInsets.all(3), // Reduced padding
                child: pw.Text(
                  'Total',
                  style: pw.TextStyle(
                    fontWeight: pw.FontWeight.bold,
                    fontSize: 8, // Reduced font size
                  ),
                  textAlign: pw.TextAlign.center,
                ),
              ),
            ],
          ),
          
          // Table Rows
          ...transactions.map((tx) => pw.TableRow(
            children: [
              pw.Padding(
                padding: const pw.EdgeInsets.all(2), // Reduced padding
                child: pw.Text(
                  _formatDate(tx['created_at'] ?? ''),
                  style: const pw.TextStyle(fontSize: 7), // Smaller font
                  textAlign: pw.TextAlign.center,
                ),
              ),
              pw.Padding(
                padding: const pw.EdgeInsets.all(2), // Reduced padding
                child: pw.Text(
                  tx['product_name'] ?? '',
                  style: const pw.TextStyle(fontSize: 7), // Smaller font
                  maxLines: 1, // Single line to save space
                ),
              ),
              pw.Padding(
                padding: const pw.EdgeInsets.all(2), // Reduced padding
                child: pw.Text(
                  tx['quantity']?.toString() ?? '',
                  style: const pw.TextStyle(fontSize: 7), // Smaller font
                  textAlign: pw.TextAlign.center,
                ),
              ),
              pw.Padding(
                padding: const pw.EdgeInsets.all(2), // Reduced padding
                child: pw.Text(
                  _getCostPrice(tx).toStringAsFixed(2),
                  style: const pw.TextStyle(fontSize: 7), // Smaller font
                  textAlign: pw.TextAlign.center,
                ),
              ),
              pw.Padding(
                padding: const pw.EdgeInsets.all(2), // Reduced padding
                child: pw.Text(
                  _getSalePrice(tx).toStringAsFixed(2),
                  style: const pw.TextStyle(fontSize: 7), // Smaller font
                  textAlign: pw.TextAlign.center,
                ),
              ),
              pw.Padding(
                padding: const pw.EdgeInsets.all(2), // Reduced padding
                child: pw.Text(
                  _calculateRowTotal(tx).toStringAsFixed(2),
                  style: const pw.TextStyle(
                    fontSize: 7, // Smaller font
                    fontWeight: pw.FontWeight.bold,
                  ),
                  textAlign: pw.TextAlign.center,
                ),
              ),
            ],
          )).toList(),
          
          // Column Totals Row - Only show on last page
          if (showTotals) pw.TableRow(
            decoration: const pw.BoxDecoration(color: PdfColors.grey100),
            children: [
              pw.Padding(
                padding: const pw.EdgeInsets.all(4),
                child: pw.Text(
                  'TOTALS:',
                  style: pw.TextStyle(
                    fontSize: 8,
                    fontWeight: pw.FontWeight.bold,
                    color: PdfColors.grey800,
                  ),
                  textAlign: pw.TextAlign.center,
                ),
              ),
              pw.Padding(
                padding: const pw.EdgeInsets.all(4),
                child: pw.Text(
                  '', // Empty for product column
                  style: const pw.TextStyle(fontSize: 7),
                ),
              ),
              pw.Padding(
                padding: const pw.EdgeInsets.all(4),
                child: pw.Text(
                  totalQuantity.toString(),
                  style: pw.TextStyle(
                    fontSize: 8,
                    fontWeight: pw.FontWeight.bold,
                    color: PdfColors.grey800,
                  ),
                  textAlign: pw.TextAlign.center,
                ),
              ),
              pw.Padding(
                padding: const pw.EdgeInsets.all(4),
                child: pw.Text(
                  '\$${totalCost.toStringAsFixed(2)}',
                  style: pw.TextStyle(
                    fontSize: 8,
                    fontWeight: pw.FontWeight.bold,
                    color: PdfColors.grey800,
                  ),
                  textAlign: pw.TextAlign.center,
                ),
              ),
              pw.Padding(
                padding: const pw.EdgeInsets.all(4),
                child: pw.Text(
                  '', // Empty for Price column - unit prices don't need totals
                  style: const pw.TextStyle(fontSize: 7),
                ),
              ),
              pw.Padding(
                padding: const pw.EdgeInsets.all(4),
                child: pw.Text(
                  '\$${grandTotal.toStringAsFixed(2)}',
                  style: pw.TextStyle(
                    fontSize: 9,
                    fontWeight: pw.FontWeight.bold,
                    color: PdfColors.grey900,
                  ),
                  textAlign: pw.TextAlign.center,
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }
  
  // Build stock summary summary
  static pw.Widget _buildStockSummarySummary(List<Map<String, dynamic>> stockData) {
    final totalSold = stockData.fold(0, (sum, row) => sum + _safeToInt(row['quantity_sold']));
    final totalRemaining = stockData.fold(0, (sum, row) => sum + _safeToInt(row['quantity_remaining']));
    final totalRevenue = stockData.fold(0.0, (sum, row) => sum + _safeToDouble(row['revenue']));
    final totalProfit = stockData.fold(0.0, (sum, row) => sum + _safeToDouble(row['profit']));
    final totalProducts = stockData.length;
    final avgRevenuePerProduct = totalProducts > 0 ? (totalRevenue / totalProducts) : 0.0;
    final profitMargin = totalRevenue > 0 ? ((totalProfit / totalRevenue) * 100) : 0.0;
    
    return pw.Container(
      padding: const pw.EdgeInsets.all(16),
      decoration: pw.BoxDecoration(
        color: PdfColors.grey50,
        borderRadius: const pw.BorderRadius.all(pw.Radius.circular(8)),
        border: pw.Border.all(color: PdfColors.grey400, width: 1),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          // Header
          pw.Container(
            width: double.infinity,
            padding: const pw.EdgeInsets.symmetric(vertical: 8, horizontal: 12),
            decoration: pw.BoxDecoration(
              color: PdfColors.grey200,
              borderRadius: const pw.BorderRadius.all(pw.Radius.circular(6)),
            ),
            child: pw.Text(
              'STOCK SUMMARY REPORT',
              style: pw.TextStyle(
                fontSize: 12,
                fontWeight: pw.FontWeight.bold,
                color: PdfColors.grey800,
              ),
              textAlign: pw.TextAlign.center,
            ),
          ),
          
          pw.SizedBox(height: 12),
          
          // Summary Grid - Professional Layout
          pw.Row(
            children: [
              // Left Column - Inventory Metrics
              pw.Expanded(
                child: pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    _buildProfessionalSummaryRow('Total Products:', totalProducts, isCurrency: false),
                    pw.SizedBox(height: 6),
                    _buildProfessionalSummaryRow('Total Sold Qty:', totalSold, isCurrency: false),
                    pw.SizedBox(height: 6),
                    _buildProfessionalSummaryRow('Total Remaining Qty:', totalRemaining, isCurrency: false),
                    pw.SizedBox(height: 6),
                    _buildProfessionalSummaryRow('Avg. Revenue/Product:', avgRevenuePerProduct),
                  ],
                ),
              ),
              
              pw.SizedBox(width: 20),
              
              // Right Column - Financial Metrics
              pw.Expanded(
                child: pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    _buildProfessionalSummaryRow('Total Revenue:', totalRevenue, isHighlight: true),
                    pw.SizedBox(height: 6),
                    _buildProfessionalSummaryRow('Total Profit:', totalProfit, isHighlight: true),
                    pw.SizedBox(height: 6),
                    _buildProfessionalSummaryRow('Profit Margin:', profitMargin, suffix: '%'),
                    pw.SizedBox(height: 8),
                    pw.Divider(color: PdfColors.grey400, thickness: 0.5),
                    pw.SizedBox(height: 8),
                    _buildProfessionalSummaryRow('GRAND TOTAL:', totalRevenue, isGrandTotal: true),
                  ],
                ),
              ),
            ],
          ),
          
          pw.SizedBox(height: 16),
          
          // Footer
          pw.Container(
            width: double.infinity,
            padding: const pw.EdgeInsets.all(12),
            decoration: pw.BoxDecoration(
              color: PdfColors.grey100,
              borderRadius: const pw.BorderRadius.all(pw.Radius.circular(6)),
              border: pw.Border.all(color: PdfColors.grey300, width: 0.5),
            ),
            child: pw.Text(
              'Stock Summary Report Generated on ${DateFormat('MMM dd, yyyy \'at\' HH:mm').format(DateTime.now())}',
              style: pw.TextStyle(
                fontSize: 9,
                fontWeight: pw.FontWeight.normal,
                color: PdfColors.grey600,
              ),
              textAlign: pw.TextAlign.center,
            ),
          ),
        ],
      ),
    );
  }

  // Build compact invoice summary
  static pw.Widget _buildCompactInvoiceSummary(List<Map<String, dynamic>> transactions) {
    final subtotal = _calculateSubtotal(transactions);
    final totalCost = _calculateTotalCost(transactions);
    final totalProfit = _calculateTotalProfit(transactions);
    final totalQuantity = _calculateTotalQuantity(transactions);
    final totalTransactions = transactions.length;
    
    return pw.Container(
      padding: const pw.EdgeInsets.all(16),
      decoration: pw.BoxDecoration(
        color: PdfColors.grey50,
        borderRadius: const pw.BorderRadius.all(pw.Radius.circular(8)),
        border: pw.Border.all(color: PdfColors.grey400, width: 1),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          // Header
          pw.Container(
            width: double.infinity,
            padding: const pw.EdgeInsets.symmetric(vertical: 8, horizontal: 12),
            decoration: pw.BoxDecoration(
              color: PdfColors.grey200,
              borderRadius: const pw.BorderRadius.all(pw.Radius.circular(6)),
            ),
            child: pw.Text(
              'TRANSACTION SUMMARY',
              style: pw.TextStyle(
                fontSize: 12,
                fontWeight: pw.FontWeight.bold,
                color: PdfColors.grey800,
              ),
              textAlign: pw.TextAlign.center,
            ),
          ),
          
          pw.SizedBox(height: 12),
          
          // Summary Grid - Professional Layout
          pw.Row(
            children: [
              // Left Column - Financial Metrics
              pw.Expanded(
                child: pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    _buildProfessionalSummaryRow('Total Revenue:', subtotal, isHighlight: true),
                    pw.SizedBox(height: 6),
                    _buildProfessionalSummaryRow('Total Cost:', totalCost),
                    pw.SizedBox(height: 6),
                    _buildProfessionalSummaryRow('Total Profit:', totalProfit, isHighlight: true),
                    pw.SizedBox(height: 8),
                    pw.Divider(color: PdfColors.grey400, thickness: 0.5),
                    pw.SizedBox(height: 8),
                    _buildProfessionalSummaryRow('GRAND TOTAL:', subtotal, isGrandTotal: true),
                  ],
                ),
              ),
              
              pw.SizedBox(width: 20),
              
              // Right Column - Transaction Metrics
              pw.Expanded(
                child: pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    _buildProfessionalSummaryRow('Total Items:', totalQuantity, isCurrency: false),
                    pw.SizedBox(height: 6),
                    _buildProfessionalSummaryRow('Transactions:', totalTransactions, isCurrency: false),
                    pw.SizedBox(height: 6),
                    _buildProfessionalSummaryRow('Avg. per Transaction:', totalTransactions > 0 ? (subtotal / totalTransactions) : 0.0),
                    pw.SizedBox(height: 6),
                    _buildProfessionalSummaryRow('Profit Margin:', subtotal > 0 ? ((totalProfit / subtotal) * 100) : 0.0, suffix: '%'),
                  ],
                ),
              ),
            ],
          ),
          
          pw.SizedBox(height: 16),
          
          // Footer
          pw.Container(
            width: double.infinity,
            padding: const pw.EdgeInsets.all(12),
            decoration: pw.BoxDecoration(
              color: PdfColors.grey100,
              borderRadius: const pw.BorderRadius.all(pw.Radius.circular(6)),
              border: pw.Border.all(color: PdfColors.grey300, width: 0.5),
            ),
            child: pw.Text(
              'Report generated on ${DateFormat('MMM dd, yyyy \'at\' HH:mm').format(DateTime.now())}',
              style: pw.TextStyle(
                fontSize: 9,
                fontWeight: pw.FontWeight.normal,
                color: PdfColors.grey600,
              ),
              textAlign: pw.TextAlign.center,
            ),
          ),
        ],
      ),
    );
  }
  
  // Build summary row helper
  static pw.Widget _buildSummaryRow(String label, dynamic value, {bool isCurrency = true}) {
    return pw.Row(
      mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
      children: [
        pw.Text(
          label,
          style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey600),
        ),
        pw.Text(
          isCurrency ? '\$${value.toStringAsFixed(2)}' : value.toString(),
          style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey600),
        ),
      ],
    );
  }
  
  // Build professional summary row helper
  static pw.Widget _buildProfessionalSummaryRow(String label, dynamic value, {
    bool isCurrency = true, 
    bool isHighlight = false, 
    bool isGrandTotal = false,
    String? suffix,
  }) {
    String displayValue;
    if (isCurrency) {
      displayValue = '\$${value.toStringAsFixed(2)}';
    } else if (suffix != null) {
      displayValue = '${value.toStringAsFixed(1)}$suffix';
    } else {
      displayValue = value.toString();
    }
    
    return pw.Container(
      padding: const pw.EdgeInsets.symmetric(vertical: 4, horizontal: 8),
      decoration: isGrandTotal ? pw.BoxDecoration(
        color: PdfColors.grey200,
        borderRadius: const pw.BorderRadius.all(pw.Radius.circular(4)),
        border: pw.Border.all(color: PdfColors.grey400, width: 1),
      ) : null,
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(
            label,
            style: pw.TextStyle(
              fontSize: isGrandTotal ? 11 : 10,
              fontWeight: isGrandTotal || isHighlight ? pw.FontWeight.bold : pw.FontWeight.normal,
              color: isGrandTotal ? PdfColors.grey900 : PdfColors.grey700,
            ),
          ),
          pw.Text(
            displayValue,
            style: pw.TextStyle(
              fontSize: isGrandTotal ? 12 : 10,
              fontWeight: isGrandTotal || isHighlight ? pw.FontWeight.bold : pw.FontWeight.normal,
              color: isGrandTotal ? PdfColors.grey900 : PdfColors.grey700,
            ),
          ),
        ],
      ),
    );
  }
  
  // Build empty state
  static pw.Widget _buildEmptyState() {
    return pw.Center(
      child: pw.Container(
        padding: const pw.EdgeInsets.all(30),
        child: pw.Column(
          children: [
            pw.Text(
              'No transactions found',
              style: const pw.TextStyle(fontSize: 14, color: PdfColors.grey),
            ),
            pw.SizedBox(height: 6),
            pw.Text(
              'There are no transactions to display in this report.',
              style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey500),
            ),
          ],
        ),
      ),
    );
  }
  
  // Pre-load business logo to avoid async issues in PDF generation
  static Future<void> _preloadBusinessLogo(Map<String, dynamic> businessData) async {
    print('🔍 PDF: Starting logo pre-loading...');
    final logoData = businessData['logo'];
    print('🔍 PDF: Logo data type: ${logoData.runtimeType}');
    print('🔍 PDF: Logo data value: $logoData');
    
    if (logoData != null && logoData.toString().isNotEmpty) {
      String logoString = logoData.toString();
      print('🔍 PDF: Logo string: $logoString');
      print('🔍 PDF: Starts with /uploads/: ${logoString.startsWith('/uploads/')}');
      
      if (logoString.startsWith('/uploads/')) {
        try {
          // Use the same pattern as product images
          final fullLogoUrl = 'https://rtailed-production.up.railway.app$logoString';
          print('🔍 PDF: Pre-loading logo from: $fullLogoUrl');
          final response = await http.get(Uri.parse(fullLogoUrl));
          print('🔍 PDF: Response status: ${response.statusCode}');
          if (response.statusCode == 200) {
            final imageBytes = response.bodyBytes;
            // Store the loaded image bytes in the business data for later use
            businessData['_logoBytes'] = imageBytes;
            print('🔍 PDF: Logo pre-loaded successfully, size: ${imageBytes.length} bytes');
          } else {
            print('🔍 PDF: Failed to pre-load logo, status: ${response.statusCode}');
            print('🔍 PDF: Response body: ${response.body}');
            print('🔍 PDF: Logo file does not exist on server - will use fallback');
            // Mark that logo loading failed so we don't try again
            businessData['_logoLoadFailed'] = true;
          }
        } catch (e) {
          print('🔍 PDF: Error pre-loading logo: $e');
          businessData['_logoLoadFailed'] = true;
        }
      } else {
        print('🔍 PDF: Logo string does not start with /uploads/, skipping pre-load');
      }
    } else {
      print('🔍 PDF: No logo data available for pre-loading');
    }
  }
  
  // Generate customer invoice PDF
  static Future<Uint8List> generateCustomerInvoice({
    required Map<String, dynamic> customerData,
    required List<Map<String, dynamic>> transactions,
    required Map<String, dynamic> businessData,
    String? startDate,
    String? endDate,
  }) async {
    final pdf = pw.Document();
    
    // Calculate totals
    final totalAmount = transactions.fold(0.0, (sum, tx) => sum + _safeToDouble(tx['total_amount']));
    final totalTransactions = transactions.length;
    final totalItems = transactions.fold(0, (sum, tx) {
      final items = tx['items'] as List<dynamic>? ?? [];
      return sum + items.fold(0, (itemSum, item) => itemSum + _safeToInt(item['quantity']));
    });
    
    // Create report title
    String reportTitle = 'CUSTOMER INVOICE';
    if (startDate != null && endDate != null) {
      reportTitle += ' - ${_formatDate(startDate)} to ${_formatDate(endDate)}';
    } else if (startDate != null) {
      reportTitle += ' - From ${_formatDate(startDate)}';
    } else if (endDate != null) {
      reportTitle += ' - Until ${_formatDate(endDate)}';
    }
    
    // Calculate pages needed
    const itemsPerPage = 15; // Reduced for better readability
    final totalPages = (transactions.length / itemsPerPage).ceil();
    
    print('🔍 PDF Customer Invoice: Creating $totalPages pages for ${transactions.length} transactions');
    
    for (int pageIndex = 0; pageIndex < totalPages; pageIndex++) {
      final startIndex = pageIndex * itemsPerPage;
      final endIndex = (startIndex + itemsPerPage).clamp(0, transactions.length);
      final pageTransactions = transactions.sublist(startIndex, endIndex);
      
      pdf.addPage(
        pw.Page(
          pageFormat: PdfPageFormat.a4,
          build: (pw.Context context) {
            return pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                // Header (only on first page)
                if (pageIndex == 0) ...[
                  _buildCustomerInvoiceHeader(customerData, businessData, reportTitle),
                  pw.SizedBox(height: 8),
                ],
                
                // Page number indicator
                if (pageIndex > 0) ...[
                  pw.Container(
                    width: double.infinity,
                    padding: const pw.EdgeInsets.all(4),
                    decoration: pw.BoxDecoration(
                      color: PdfColors.grey100,
                      borderRadius: const pw.BorderRadius.all(pw.Radius.circular(4)),
                    ),
                    child: pw.Text(
                      'Page ${pageIndex + 1} of $totalPages',
                      style: const pw.TextStyle(
                        fontSize: 8,
                        fontWeight: pw.FontWeight.bold,
                        color: PdfColors.grey700,
                      ),
                      textAlign: pw.TextAlign.center,
                    ),
                  ),
                  pw.SizedBox(height: 6),
                ],
                
                // Transactions Table for this page
                _buildCustomerInvoiceTable(pageTransactions, showTotals: pageIndex == totalPages - 1, allTransactions: transactions),
                
                // Summary (only on last page)
                if (pageIndex == totalPages - 1) ...[
                  pw.SizedBox(height: 8),
                  _buildCustomerInvoiceSummary(transactions, customerData),
                ],
              ],
            );
          },
        ),
      );
    }
    
    return pdf.save();
  }
  
  // Build customer invoice header
  static pw.Widget _buildCustomerInvoiceHeader(Map<String, dynamic> customerData, Map<String, dynamic> businessData, String reportTitle) {
    final businessName = businessData['name'] ?? 'XXX';
    final primaryColor = _parseColor(businessData['primary_color'] ?? '#1976D2');
    final tagline = businessData['tagline'] ?? 'XXX';
    final customerName = customerData['name'] ?? 'Customer';
    final customerEmail = customerData['email'] ?? '';
    final customerPhone = customerData['phone'] ?? '';
    final customerAddress = customerData['address'] ?? '';
    
    return pw.Container(
      width: double.infinity,
      padding: const pw.EdgeInsets.all(12),
      decoration: pw.BoxDecoration(
        color: primaryColor,
        borderRadius: const pw.BorderRadius.all(pw.Radius.circular(6)),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          // Business Info Row
          pw.Row(
            children: [
              // Business Logo
              _buildBusinessLogo(businessData, primaryColor),
              
              pw.SizedBox(width: 12),
              
              // Business Info
              pw.Expanded(
                child: pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text(
                      businessName,
                      style: pw.TextStyle(
                        color: PdfColors.white,
                        fontSize: 16,
                        fontWeight: pw.FontWeight.bold,
                      ),
                      maxLines: 1,
                    ),
                    pw.Text(
                      tagline,
                      style: pw.TextStyle(
                        color: PdfColors.grey200,
                        fontSize: 10,
                        fontWeight: pw.FontWeight.normal,
                      ),
                    ),
                  ],
                ),
              ),
              
              // Customer Info
              pw.Expanded(
                child: pw.Container(
                  padding: const pw.EdgeInsets.all(8),
                  decoration: pw.BoxDecoration(
                    color: PdfColors.grey100,
                    borderRadius: const pw.BorderRadius.all(pw.Radius.circular(4)),
                  ),
                  child: pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text(
                        'BILL TO:',
                        style: pw.TextStyle(
                          color: PdfColors.white,
                          fontSize: 8,
                          fontWeight: pw.FontWeight.bold,
                        ),
                      ),
                      pw.SizedBox(height: 4),
                      pw.Text(
                        customerName,
                        style: pw.TextStyle(
                          color: PdfColors.white,
                          fontSize: 12,
                          fontWeight: pw.FontWeight.bold,
                        ),
                      ),
                      if (customerEmail.isNotEmpty) ...[
                        pw.SizedBox(height: 2),
                        pw.Text(
                          customerEmail,
                          style: pw.TextStyle(
                            color: PdfColors.grey200,
                            fontSize: 9,
                          ),
                        ),
                      ],
                      if (customerPhone.isNotEmpty) ...[
                        pw.SizedBox(height: 2),
                        pw.Text(
                          customerPhone,
                          style: pw.TextStyle(
                            color: PdfColors.grey200,
                            fontSize: 9,
                          ),
                        ),
                      ],
                      if (customerAddress.isNotEmpty) ...[
                        pw.SizedBox(height: 2),
                        pw.Text(
                          customerAddress,
                          style: pw.TextStyle(
                            color: PdfColors.grey200,
                            fontSize: 9,
                          ),
                          maxLines: 2,
                        ),
                      ],
                    ],
                  ),
                ),
              ),
            ],
          ),
          
          pw.SizedBox(height: 8),
          
          // Report Title
          pw.Container(
            width: double.infinity,
            padding: const pw.EdgeInsets.symmetric(horizontal: 12, vertical: 6),
            child: pw.Text(
              reportTitle,
              style: pw.TextStyle(
                color: PdfColors.white,
                fontSize: 11,
                fontWeight: pw.FontWeight.bold,
              ),
              textAlign: pw.TextAlign.center,
            ),
          ),
        ],
      ),
    );
  }
  
  // Build customer invoice table
  static pw.Widget _buildCustomerInvoiceTable(List<Map<String, dynamic>> transactions, {
    bool showTotals = true,
    List<Map<String, dynamic>>? allTransactions,
  }) {
    // Calculate totals from ALL data if provided
    final dataForTotals = allTransactions ?? transactions;
    final totalAmount = dataForTotals.fold(0.0, (sum, tx) => sum + _safeToDouble(tx['total_amount']));
    final totalTransactions = dataForTotals.length;
    final totalItems = dataForTotals.fold(0, (sum, tx) {
      final items = tx['items'] as List<dynamic>? ?? [];
      return sum + items.fold(0, (itemSum, item) => itemSum + _safeToInt(item['quantity']));
    });
    
    return pw.Container(
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.grey400),
        borderRadius: const pw.BorderRadius.all(pw.Radius.circular(6)),
      ),
      child: pw.Table(
        border: pw.TableBorder.all(color: PdfColors.grey400, width: 0.3),
        columnWidths: const {
          0: pw.FlexColumnWidth(1), // Date
          1: pw.FlexColumnWidth(1.5), // Transaction ID
          2: pw.FlexColumnWidth(2), // Products
          3: pw.FlexColumnWidth(0.8), // Items
          4: pw.FlexColumnWidth(1), // Payment
          5: pw.FlexColumnWidth(1.2), // Total
        },
        children: [
          // Table Header
          pw.TableRow(
            decoration: const pw.BoxDecoration(color: PdfColors.grey200),
            children: [
              pw.Padding(
                padding: const pw.EdgeInsets.all(3),
                child: pw.Text(
                  'Date',
                  style: pw.TextStyle(
                    fontWeight: pw.FontWeight.bold,
                    fontSize: 8,
                  ),
                  textAlign: pw.TextAlign.center,
                ),
              ),
              pw.Padding(
                padding: const pw.EdgeInsets.all(3),
                child: pw.Text(
                  'Transaction',
                  style: pw.TextStyle(
                    fontWeight: pw.FontWeight.bold,
                    fontSize: 8,
                  ),
                  textAlign: pw.TextAlign.center,
                ),
              ),
              pw.Padding(
                padding: const pw.EdgeInsets.all(3),
                child: pw.Text(
                  'Products',
                  style: pw.TextStyle(
                    fontWeight: pw.FontWeight.bold,
                    fontSize: 8,
                  ),
                ),
              ),
              pw.Padding(
                padding: const pw.EdgeInsets.all(3),
                child: pw.Text(
                  'Items',
                  style: pw.TextStyle(
                    fontWeight: pw.FontWeight.bold,
                    fontSize: 8,
                  ),
                  textAlign: pw.TextAlign.center,
                ),
              ),
              pw.Padding(
                padding: const pw.EdgeInsets.all(3),
                child: pw.Text(
                  'Payment',
                  style: pw.TextStyle(
                    fontWeight: pw.FontWeight.bold,
                    fontSize: 8,
                  ),
                  textAlign: pw.TextAlign.center,
                ),
              ),
              pw.Padding(
                padding: const pw.EdgeInsets.all(3),
                child: pw.Text(
                  'Total',
                  style: pw.TextStyle(
                    fontWeight: pw.FontWeight.bold,
                    fontSize: 8,
                  ),
                  textAlign: pw.TextAlign.center,
                ),
              ),
            ],
          ),
          
          // Table Rows
          ...transactions.map((tx) => pw.TableRow(
            children: [
              pw.Padding(
                padding: const pw.EdgeInsets.all(2),
                child: pw.Text(
                  _formatDate(tx['created_at'] ?? ''),
                  style: const pw.TextStyle(fontSize: 7),
                  textAlign: pw.TextAlign.center,
                ),
              ),
              pw.Padding(
                padding: const pw.EdgeInsets.all(2),
                child: pw.Text(
                  '#${tx['id']}',
                  style: const pw.TextStyle(fontSize: 7),
                  textAlign: pw.TextAlign.center,
                ),
              ),
              pw.Padding(
                padding: const pw.EdgeInsets.all(2),
                child: pw.Text(
                  _getTransactionProducts(tx),
                  style: const pw.TextStyle(fontSize: 7),
                  maxLines: 2,
                ),
              ),
              pw.Padding(
                padding: const pw.EdgeInsets.all(2),
                child: pw.Text(
                  _getTransactionItemCount(tx).toString(),
                  style: const pw.TextStyle(fontSize: 7),
                  textAlign: pw.TextAlign.center,
                ),
              ),
              pw.Padding(
                padding: const pw.EdgeInsets.all(2),
                child: pw.Text(
                  tx['payment_method'] ?? '',
                  style: const pw.TextStyle(fontSize: 7),
                  textAlign: pw.TextAlign.center,
                ),
              ),
              pw.Padding(
                padding: const pw.EdgeInsets.all(2),
                child: pw.Text(
                  '\$${_safeToDouble(tx['total_amount']).toStringAsFixed(2)}',
                  style: const pw.TextStyle(
                    fontSize: 7,
                    fontWeight: pw.FontWeight.bold,
                  ),
                  textAlign: pw.TextAlign.center,
                ),
              ),
            ],
          )).toList(),
          
          // Column Totals Row - Only show on last page
          if (showTotals) pw.TableRow(
            decoration: const pw.BoxDecoration(color: PdfColors.grey100),
            children: [
              pw.Padding(
                padding: const pw.EdgeInsets.all(4),
                child: pw.Text(
                  'TOTALS:',
                  style: pw.TextStyle(
                    fontSize: 8,
                    fontWeight: pw.FontWeight.bold,
                    color: PdfColors.grey800,
                  ),
                  textAlign: pw.TextAlign.center,
                ),
              ),
              pw.Padding(
                padding: const pw.EdgeInsets.all(4),
                child: pw.Text(
                  totalTransactions.toString(),
                  style: pw.TextStyle(
                    fontSize: 8,
                    fontWeight: pw.FontWeight.bold,
                    color: PdfColors.grey800,
                  ),
                  textAlign: pw.TextAlign.center,
                ),
              ),
              pw.Padding(
                padding: const pw.EdgeInsets.all(4),
                child: pw.Text(
                  '', // Empty for products column
                  style: const pw.TextStyle(fontSize: 7),
                ),
              ),
              pw.Padding(
                padding: const pw.EdgeInsets.all(4),
                child: pw.Text(
                  totalItems.toString(),
                  style: pw.TextStyle(
                    fontSize: 8,
                    fontWeight: pw.FontWeight.bold,
                    color: PdfColors.grey800,
                  ),
                  textAlign: pw.TextAlign.center,
                ),
              ),
              pw.Padding(
                padding: const pw.EdgeInsets.all(4),
                child: pw.Text(
                  '', // Empty for payment column
                  style: const pw.TextStyle(fontSize: 7),
                ),
              ),
              pw.Padding(
                padding: const pw.EdgeInsets.all(4),
                child: pw.Text(
                  '\$${totalAmount.toStringAsFixed(2)}',
                  style: pw.TextStyle(
                    fontSize: 9,
                    fontWeight: pw.FontWeight.bold,
                    color: PdfColors.grey900,
                  ),
                  textAlign: pw.TextAlign.center,
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }
  
  // Build customer invoice summary
  static pw.Widget _buildCustomerInvoiceSummary(List<Map<String, dynamic>> transactions, Map<String, dynamic> customerData) {
    final totalAmount = transactions.fold(0.0, (sum, tx) => sum + _safeToDouble(tx['total_amount']));
    final totalTransactions = transactions.length;
    final totalItems = transactions.fold(0, (sum, tx) {
      final items = tx['items'] as List<dynamic>? ?? [];
      return sum + items.fold(0, (itemSum, item) => itemSum + _safeToInt(item['quantity']));
    });
    final avgTransactionValue = totalTransactions > 0 ? totalAmount / totalTransactions : 0.0;
    
    return pw.Container(
      padding: const pw.EdgeInsets.all(16),
      decoration: pw.BoxDecoration(
        color: PdfColors.grey50,
        borderRadius: const pw.BorderRadius.all(pw.Radius.circular(8)),
        border: pw.Border.all(color: PdfColors.grey400, width: 1),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          // Header
          pw.Container(
            width: double.infinity,
            padding: const pw.EdgeInsets.symmetric(vertical: 8, horizontal: 12),
            decoration: pw.BoxDecoration(
              color: PdfColors.grey200,
              borderRadius: const pw.BorderRadius.all(pw.Radius.circular(6)),
            ),
            child: pw.Text(
              'INVOICE SUMMARY',
              style: pw.TextStyle(
                fontSize: 12,
                fontWeight: pw.FontWeight.bold,
                color: PdfColors.grey800,
              ),
              textAlign: pw.TextAlign.center,
            ),
          ),
          
          pw.SizedBox(height: 12),
          
          // Summary Grid
          pw.Row(
            children: [
              // Left Column
              pw.Expanded(
                child: pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    _buildProfessionalSummaryRow('Customer:', customerData['name'] ?? 'N/A', isCurrency: false),
                    pw.SizedBox(height: 6),
                    _buildProfessionalSummaryRow('Total Transactions:', totalTransactions, isCurrency: false),
                    pw.SizedBox(height: 6),
                    _buildProfessionalSummaryRow('Total Items:', totalItems, isCurrency: false),
                    pw.SizedBox(height: 6),
                    _buildProfessionalSummaryRow('Avg. per Transaction:', avgTransactionValue),
                  ],
                ),
              ),
              
              pw.SizedBox(width: 20),
              
              // Right Column
              pw.Expanded(
                child: pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    _buildProfessionalSummaryRow('Total Amount:', totalAmount, isHighlight: true),
                    pw.SizedBox(height: 8),
                    pw.Divider(color: PdfColors.grey400, thickness: 0.5),
                    pw.SizedBox(height: 8),
                    _buildProfessionalSummaryRow('GRAND TOTAL:', totalAmount, isGrandTotal: true),
                  ],
                ),
              ),
            ],
          ),
          
          pw.SizedBox(height: 16),
          
          // Footer
          pw.Container(
            width: double.infinity,
            padding: const pw.EdgeInsets.symmetric(vertical: 6, horizontal: 8),
            decoration: pw.BoxDecoration(
              color: PdfColors.grey100,
              borderRadius: const pw.BorderRadius.all(pw.Radius.circular(4)),
            ),
            child: pw.Text(
              'Invoice generated on ${DateFormat('yyyy-MM-dd HH:mm').format(DateTime.now())}',
              style: const pw.TextStyle(
                fontSize: 8,
                color: PdfColors.grey600,
              ),
              textAlign: pw.TextAlign.center,
            ),
          ),
        ],
      ),
    );
  }
  
  // Helper function to get transaction products summary
  static String _getTransactionProducts(Map<String, dynamic> transaction) {
    final items = transaction['items'] as List<dynamic>? ?? [];
    if (items.isEmpty) return 'No items';
    
    if (items.length == 1) {
      return items[0]['product_name'] ?? 'Unknown Product';
    } else {
      return '${items.length} products';
    }
  }
  
  // Helper function to get transaction item count
  static int _getTransactionItemCount(Map<String, dynamic> transaction) {
    final items = transaction['items'] as List<dynamic>? ?? [];
    return items.fold(0, (sum, item) => sum + _safeToInt(item['quantity']));
  }
  
  // Build business logo widget
  static pw.Widget _buildBusinessLogo(Map<String, dynamic> businessInfo, PdfColor primaryColor) {
    final businessName = businessInfo['name'] ?? 'XXX';
    final logoUrl = businessInfo['logo_url'];
    final logoData = businessInfo['logo']; // Can be base64 data or file path
    final preloadedBytes = businessInfo['_logoBytes'] as Uint8List?; // Pre-loaded image bytes
    final logoLoadFailed = businessInfo['_logoLoadFailed'] == true; // Flag if logo loading failed
    
    print('🔍 PDF Logo: logo_url = $logoUrl');
    print('🔍 PDF Logo: logo data available = ${logoData != null}');
    print('🔍 PDF Logo: pre-loaded bytes available = ${preloadedBytes != null}');
    print('🔍 PDF Logo: logo load failed = $logoLoadFailed');
    
    // First check if we have pre-loaded bytes (for file path logos)
    if (preloadedBytes != null) {
      print('🔍 PDF Logo: Using pre-loaded image bytes');
      return pw.Container(
        width: 30,
        height: 30,
        decoration: pw.BoxDecoration(
          borderRadius: const pw.BorderRadius.all(pw.Radius.circular(4)),
        ),
        child: pw.Image(
          pw.MemoryImage(preloadedBytes),
          fit: pw.BoxFit.cover,
        ),
      );
    }
    
    // If logo loading failed, skip trying to process it and go straight to fallback
    if (logoLoadFailed) {
      print('🔍 PDF Logo: Logo loading failed, using fallback');
      // Fall through to fallback
    } else if (logoData != null && logoData.toString().isNotEmpty) {
      try {
        String logoString = logoData.toString();
        
        // Check if it's base64 data URL
        if (logoString.startsWith('data:image/')) {
          // It's base64 data URL
          String base64Data = logoString.split(',')[1];
          print('🔍 PDF Logo: Using base64 logo data');
          
          return pw.Container(
            width: 30,
            height: 30,
            decoration: pw.BoxDecoration(
              borderRadius: const pw.BorderRadius.all(pw.Radius.circular(4)),
            ),
            child: pw.Image(
              pw.MemoryImage(
                base64Decode(base64Data)
              ),
              fit: pw.BoxFit.cover,
            ),
          );
        } else {
          // Try to decode as base64 directly
          print('🔍 PDF Logo: Trying to decode as base64');
          try {
            return pw.Container(
              width: 30,
              height: 30,
              decoration: pw.BoxDecoration(
                borderRadius: const pw.BorderRadius.all(pw.Radius.circular(4)),
              ),
              child: pw.Image(
                pw.MemoryImage(
                  base64Decode(logoString)
                ),
                fit: pw.BoxFit.cover,
              ),
            );
          } catch (e) {
            print('🔍 PDF Logo: Error decoding base64: $e');
            // Fall back to text initials
          }
        }
      } catch (e) {
        print('🔍 PDF Logo: Error loading logo: $e');
        // Fall back to text initials
      }
    }
    
    // Fallback to text initials
    return pw.Container(
      width: 30, // Reduced size
      height: 30, // Reduced size
      decoration: pw.BoxDecoration(
        color: PdfColors.white,
        borderRadius: const pw.BorderRadius.all(pw.Radius.circular(4)), // Smaller radius
      ),
      child: pw.Center(
        child: pw.Text(
          businessName.isNotEmpty && businessName != 'XXX' 
            ? businessName.substring(0, 1).toUpperCase()
            : 'X',
          style: pw.TextStyle(
            fontSize: 12, // Reduced font size
            fontWeight: pw.FontWeight.bold,
            color: primaryColor,
          ),
        ),
      ),
    );
  }

  // Helper methods
  static String _formatDate(String timestamp) {
    try {
      if (timestamp.isEmpty) return '';
      final dateTime = DateTime.parse(timestamp);
      final localDateTime = dateTime.toLocal();
      return '${localDateTime.day.toString().padLeft(2, '0')}/${localDateTime.month.toString().padLeft(2, '0')}/${localDateTime.year} ${localDateTime.hour.toString().padLeft(2, '0')}:${localDateTime.minute.toString().padLeft(2, '0')}';
    } catch (e) {
      return timestamp;
    }
  }
  
  static double _safeToDouble(dynamic value) {
    if (value == null) return 0.0;
    if (value is num) return value.toDouble();
    if (value is String) return double.tryParse(value) ?? 0.0;
    return 0.0;
  }
  
  // Get cost price from transaction data
  static double _getCostPrice(Map<String, dynamic> transaction) {
    // Try to get cost price from various possible fields
    final costPrice = transaction['product_cost_price'] ?? 
                     transaction['cost_price'] ?? 
                     transaction['unit_cost'] ?? 0.0;
    return _safeToDouble(costPrice);
  }
  
  // Get sale price from transaction data
  static double _getSalePrice(Map<String, dynamic> transaction) {
    // Try to get sale price from various possible fields
    final salePrice = transaction['sale_unit_price'] ?? 
                     transaction['unit_price'] ?? 
                     transaction['product_price'] ?? 
                     transaction['price'] ?? 0.0;
    return _safeToDouble(salePrice);
  }
  
  // Calculate row total
  static double _calculateRowTotal(Map<String, dynamic> transaction) {
    final quantity = _safeToInt(transaction['quantity']);
    final salePrice = _getSalePrice(transaction);
    return quantity * salePrice;
  }
  
  // Calculate subtotal
  static double _calculateSubtotal(List<Map<String, dynamic>> transactions) {
    return transactions.fold(0.0, (sum, tx) => sum + _calculateRowTotal(tx));
  }
  
  // Calculate total cost
  static double _calculateTotalCost(List<Map<String, dynamic>> transactions) {
    return transactions.fold(0.0, (sum, tx) {
      final quantity = _safeToInt(tx['quantity']);
      final costPrice = _getCostPrice(tx);
      return sum + (quantity * costPrice);
    });
  }
  
  // Calculate total profit
  static double _calculateTotalProfit(List<Map<String, dynamic>> transactions) {
    return transactions.fold(0.0, (sum, tx) => sum + _safeToDouble(tx['profit'] ?? 0));
  }
  
  // Calculate total quantity
  static int _calculateTotalQuantity(List<Map<String, dynamic>> transactions) {
    return transactions.fold(0, (sum, tx) => sum + (_safeToInt(tx['quantity'])));
  }
  
  static int _safeToInt(dynamic value) {
    if (value == null) return 0;
    if (value is int) return value;
    if (value is num) return value.toInt();
    if (value is String) return int.tryParse(value) ?? 0;
    return 0;
  }
  
  static PdfColor _parseColor(String hex) {
    try {
      hex = hex.replaceAll('#', '');
      if (hex.length == 6) {
        hex = 'FF$hex';
      }
      return PdfColor.fromInt(int.parse(hex, radix: 16));
    } catch (e) {
      return PdfColors.blue;
    }
  }
  

}
