[build]
builder = "nixpacks"
source = "backend"
nixpacksConfigPath = "backend/.nixpacks"
ignore = [
  "pubspec.yaml",
  "pubspec.lock", 
  "*.dart",
  "frontend/",
  "lib/",
  "web/",
  "build/",
  ".dart_tool/",
  ".flutter-plugins",
  ".flutter-plugins-dependencies",
  "*"
]
providers = ["nodejs"]
rootDir = "backend"

[phases.setup]
nixPkgs = ["nodejs_22", "npm-9_x"]

[phases.install]
cmds = ["npm i"]

[phases.build]
cmds = ["echo 'Building Node.js backend...'"]

[start]
cmd = "npm start"

[phases.setup]
nixPkgs = ["nodejs_22", "npm-9_x"]

[phases.install]
cmds = ["npm i"]

[phases.build]
cmds = ["echo 'Building Node.js backend...'"]

[start]
cmd = "npm start"

[phases.setup]
nixPkgs = ["nodejs_22", "npm-9_x"]

[phases.install]
cmds = ["npm i"]

[phases.build]
cmds = ["echo 'Building Node.js backend...'"]

[start]
cmd = "npm start"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 600
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 