[build]
builder = "nixpacks"
source = "./backend"
nixpacksConfigPath = "./backend/.nixpacks"
ignore = [
  "frontend/", 
  "*.dart", 
  "pubspec.yaml", 
  "pubspec.lock",
  "lib/", 
  "web/",
  "*.js",
  "*.html", 
  "*.css",
  "*.png",
  "*.ico",
  "*.json",
  "!backend/package.json",
  "!backend/package-lock.json"
]

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 600
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 