[build]
builder = "nixpacks"
providers = ["nodejs"]

[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["echo 'Building Node.js backend...'"]

[start]
cmd = "npm start"

[phases.setup]
nixPkgs = ["nodejs_22", "npm-9_x"]

[phases.install]
cmds = ["npm i"]

[phases.build]
cmds = ["echo 'Building Node.js backend...'"]

[start]
cmd = "npm start"

[phases.setup]
nixPkgs = ["nodejs_22", "npm-9_x"]

[phases.install]
cmds = ["npm i"]

[phases.build]
cmds = ["echo 'Building Node.js backend...'"]

[start]
cmd = "npm start"

[phases.setup]
nixPkgs = ["nodejs_22", "npm-9_x"]

[phases.install]
cmds = ["npm i"]

[phases.build]
cmds = ["echo 'Building Node.js backend...'"]

[start]
cmd = "npm start"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 600
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 