[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[[services]]
name = "backend"
sourceDir = "backend"

[services.env]
NODE_ENV = "production"
RAILWAY_VOLUME_MOUNT_PATH = "/data"

[[volumes]]
name = "uploads"
mountPath = "/data/uploads" 