providers = ["node"]

[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmds = [
  "npm ci",
  "node setup_uploads_directories.js || true"
]

[phases.build]
cmds = ["echo skipping build phase"]

[start]
cmd = "npm start"
