import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:retail_management/providers/settings_provider.dart';

final Map<String, Map<String, String>> translations = {
  'English': {
    'Settings': 'Settings',
    'Profile Settings': 'Profile Settings',
    'Preferences': 'Preferences',
    'System Information': 'System Information',
    'Dark Mode': 'Dark Mode',
    'Enable dark theme': 'Enable dark theme',
    'Notifications': 'Notifications',
    'Enable push notifications': 'Enable push notifications',
    'My Notifications': 'My Notifications',
    'Send Message': 'Send Message',
    'Send Message to Cashiers': 'Send Message to Cashiers',
    'Title': 'Title',
    'Message': 'Message',
    'Select Cashiers': 'Select Cashiers',
    'Send to all cashiers': 'Send to all cashiers',
    'No cashiers found': 'No cashiers found',
    'Send Notification': 'Send Notification',
    'Notification sent successfully': 'Notification sent successfully',
    'Mark all as read': 'Mark all as read',
    'No notifications': 'No notifications',
    'Mark as read': 'Mark as read',
    'Priority': 'Priority',
    'Low': 'Low',
    'Medium': 'Medium',
    'High': 'High',
    'Urgent': 'Urgent',
    'Info': 'Info',
    'Warning': 'Warning',
    'Error': 'Error',
    'Success': 'Success',
    'Language': 'Language',
    'Currency': 'Currency',
    'Update Profile': 'Update Profile',
    'Login': 'Login',
    'Logout': 'Logout',
    'Dashboard': 'Dashboard',
    'POS': 'POS',
    'Inventory': 'Inventory',
    'Reports': 'Reports',
    'Add Product': 'Add Product',
    'Product': 'Product',
    'Products': 'Products',
    'Quantity': 'Quantity',
    'Price': 'Price',
    'Total': 'Total',
    'Customer': 'Customer',
    'Sale': 'Sale',
    'Wholesale': 'Wholesale',
    'Retail': 'Retail',
    'Complete Sale': 'Complete Sale',
    'Cancel': 'Cancel',
    'Add': 'Add',
    'Remove': 'Remove',
    'Search': 'Search',
    'Filter': 'Filter',
    'Date': 'Date',
    'Type': 'Type',
    'Profit': 'Profit',
    'Notes': 'Notes',
    'Mode': 'Mode',
    'Payment Method': 'Payment Method',
    'Order Summary': 'Order Summary',
    'Checkout': 'Checkout',
    'Cart is empty': 'Cart is empty',
    'Add products to get started': 'Add products to get started',
    'Set Quantity': 'Set Quantity',
    'Enter quantity': 'Enter quantity',
    'Set': 'Set',
    'Clear Cart': 'Clear Cart',
    'Shopping Cart': 'Shopping Cart',
    'Cost': 'Cost',
    'Stock': 'Stock',
    'LOW': 'LOW',
    'OUT': 'OUT',
    'Sale completed successfully!': 'Sale completed successfully!',
    'Error processing sale': 'Error processing sale',
    'Required, ≥': 'Required, ≥',
    'Must be ≥ cost × quantity': 'Must be ≥ cost × quantity',
    'Total entered amount must be at least the combined cost!': 'Total entered amount must be at least the combined cost!',
    'Customer Name': 'Customer Name',
    'Customer Phone': 'Customer Phone',
    'New Customer': 'New Customer',
    'Cancel New Customer': 'Cancel New Customer',
    'New Customer Name': 'New Customer Name',
    'New Customer Phone': 'New Customer Phone',
    'Enter new customer name': 'Enter new customer name',
    'Enter phone (optional)': 'Enter phone (optional)',
    'Required for credit sales': 'Required for credit sales',
    'Select or enter customer name': 'Select or enter customer name',
    'Complete your sale': 'Complete your sale',
    'Enter Custom Prices': 'Enter Custom Prices',
    'Custom Price': 'Custom Price',
    'Enter custom price': 'Enter custom price',
    'Products Sold': 'Products Sold',
    'Unique Customers': 'Unique Customers',
    'Cash in Hand': 'Cash in Hand',
    'Total Orders': 'Total Orders',
    'Total Sales': 'Total Sales',
    'Total Credits': 'Total Credits',
    'Cash (Balance Sheet)': 'Cash (Balance Sheet)',
    'Payment Methods': 'Payment Methods',
    'Product Transactions': 'Product Transactions',
    'No transactions found for this product.': 'No transactions found for this product.',
    'Method': 'Method',
    'Percentage': 'Percentage',
    'Total Amount': 'Total Amount',
    'Sale ID': 'Sale ID',
    'Status': 'Status',
    'Unit Price': 'Unit Price',
    'Total Price': 'Total Price',
    'No payment method data': 'No payment method data',
    'Business Report': 'Business Report',
    'Today': 'Today',
    'This Week': 'This Week',
    'Last 7 Days': 'Last 7 Days',
    'Custom Range': 'Custom Range',
    'All Time': 'All Time',
    'All history': 'All history',
    'No report data. Adjust filters and try again.': 'No report data. Adjust filters and try again.',
    'No recent transactions.': 'No recent transactions.',
    'No transactions today.': 'No transactions today.',
    'No transactions this week.': 'No transactions this week.',
    'No transactions for selected dates.': 'No transactions for selected dates.',
    'No products found': 'No products found',
    'Low Stock': 'Low Stock',
    'In Stock': 'In Stock',
    'Edit Product': 'Edit Product',
    'Delete Product': 'Delete Product',
    'Are you sure you want to delete this product?': 'Are you sure you want to delete this product?',
    'This action cannot be undone.': 'This action cannot be undone.',
    'Add New Product': 'Add New Product',
    'Create a new product in your inventory': 'Create a new product in your inventory',
    'Update product information': 'Update product information',
    'Product Name *': 'Product Name *',
    'SKU *': 'SKU *',
    'Description': 'Description',
    'Price *': 'Price *',
    'Cost *': 'Cost *',
    'Stock Quantity': 'Stock Quantity',
    'Category': 'Category',
    'Add Image': 'Add Image',
    'Add Product': 'Add Product',
    'Update Product': 'Update Product',
    'orders': 'orders',
    'avg': 'avg',
    'active': 'active',
    'low stock': 'low stock',
    'Gross profit': 'Gross profit',
    'Available': 'Available',
    'Receivables': 'Receivables',
    'Credit Section': 'Credit Section',
    'Pay': 'Pay',
    'Settled': 'Settled',
    'Settled on': 'Settled on',
    'Payment Error': 'Payment Error',
    'OK': 'OK',
    'Unknown': 'Unknown',
    'Yesterday': 'Yesterday',
    'days ago': 'days ago',
    'Credit Transactions for': 'Credit Transactions for',
    'No product details available': 'No product details available',
    'Payment History:': 'Payment History:',
    'Close': 'Close',
    // --- Admin Dashboard Translations ---
    'Overview': 'Overview',
    'Businesses': 'Businesses',
    'Users & Security': 'Users & Security',
    'Data Management': 'Data Management',
    'System Health': 'System Health',
    'Billing Overview': 'Billing Overview',
    'Billing information will appear here': 'Billing information will appear here',
    'User Management': 'User Management',
    'Manage Users': 'Manage Users',
    'Audit Logs': 'Audit Logs',
    'View security audit logs': 'View security audit logs',
    'Access Control': 'Access Control',
    'Manage role permissions': 'Manage role permissions',
    'System Settings': 'System Settings',
    'Configure system parameters': 'Configure system parameters',
    'Admin Codes': 'Admin Codes',
    'Update Admin Code': 'Update Admin Code',
    'Business Branding': 'Business Branding',
    'Health': 'Health',
    'Alerts': 'Alerts',
    'Billing': 'Billing',
    'Users': 'Users',
    'Data': 'Data',
    'System': 'System',
    'Codes': 'Codes',
    'Brand': 'Brand',
    'Account': 'Account',
    'Refresh': 'Refresh',
    'Profile': 'Profile',
    // --- Admin Dashboard Translations ---
    'General': 'General',
    'Damages': 'Damages',
    'Credit Management': 'Credit Management',
    'Toggle Credit Section': 'Toggle Credit Section',
    'Credit Sales': 'Credit Sales',
    'Outstanding': 'Outstanding',
    'View Details': 'View Details',
    'Please enter a valid payment amount': 'Please enter a valid payment amount',
    'Payment amount cannot exceed outstanding amount': 'Payment amount cannot exceed outstanding amount',
    'No phone': 'No phone',
    'No email': 'No email',
    'sales': 'sales',
    // --- Accounting Translations ---
    'General Ledger': 'General Ledger',
    'Total Income': 'Total Income',
    'Total Expenses': 'Total Expenses',
    'Net Profit': 'Net Profit',
    'Cash': 'Cash',
    'Receivables': 'Receivables',
    'Liabilities': 'Liabilities',
    'Inflow': 'Inflow',
    'Outflow': 'Outflow',
    // --- Damaged Products Translations ---
    'Damage Type': 'Damage Type',
    // --- Reports Screen Translations ---
    'Filter by Date': 'Filter by Date',
    'Filter by Cashier': 'Filter by Cashier',
    'Business Report': 'Business Report',
    'Sales Report': 'Sales Report',
    'Balance Sheet': 'Balance Sheet',
    'Damaged Products Report': 'Damaged Products Report',
    'Product Transactions': 'Product Transactions',
    'No transactions found for this product': 'No transactions found for this product',
    // --- Inventory Screen Translations ---
    'Filters': 'Filters',
    'Search Products': 'Search Products',
    'Inventory Report': 'Inventory Report',
    'Todays Transactions': 'Todays Transactions',
    'This Weeks Transactions': 'This Weeks Transactions',
    'Filter Transactions by Date': 'Filter Transactions by Date',
    'No transactions for selected dates': 'No transactions for selected dates',
    'No recent transactions': 'No recent transactions',
    'No transactions today': 'No transactions today',
    'No transactions this week': 'No transactions this week',
    'No stock summary data': 'No stock summary data',
    'No report data, adjust filters and try again': 'No report data, adjust filters and try again',
    'Loading products...': 'Loading products...',
    'Found': 'Found',
    'Low': 'Low',
    'Search & Filters': 'Search & Filters',
    // --- Dashboard Screen Translations ---
    'Monitor your business performance': 'Monitor your business performance',
    'Recent Sales': 'Recent Sales',
    'Low Stock Alert': 'Low Stock Alert',
    'Total Profit': 'Total Profit',
    'Average Order Value': 'Average Order Value',
    'Low Stock Count': 'Low Stock Count',
    'Cash on Hand': 'Cash on Hand',
    // --- POS Screen Translations ---
    'Uncategorized': 'Uncategorized',
    'Search Products': 'Search Products',
    'Select Category': 'Select Category',
    'Add to Cart': 'Add to Cart',
    'Remove from Cart': 'Remove from Cart',
    'Set Quantity': 'Set Quantity',
    'Enter quantity': 'Enter quantity',
    'Clear Cart': 'Clear Cart',
    'Order Summary': 'Order Summary',
    'Payment Method': 'Payment Method',
    'Customer Name': 'Customer Name',
    'Customer Phone': 'Customer Phone',
    'New Customer': 'New Customer',
    'Complete Sale': 'Complete Sale',
    'Remove': 'Remove',
    'Search': 'Search',
    'Filter': 'Filter',
    'Error loading dashboard data': 'Error loading dashboard data',
    // --- POS Additional Translations ---
    'Point of Sale': 'Point of Sale',
    'Sale Mode': 'Sale Mode',
    'Wholesale Quantity': 'Wholesale Quantity',
    'Enter Wholesale Quantity': 'Enter Wholesale Quantity',
    // --- Outstanding Credit Translations ---
    'Total Outstanding': 'Total Outstanding',
    'Outstanding Amount': 'Outstanding Amount',
    'Credit Customers': 'Credit Customers',
    'No credit customers found.': 'No credit customers found.',
  },
  'Somali': {
    'Settings': 'Dejinta',
    'Profile Settings': 'Dejinta Xogta',
    'Preferences': 'Doorashooyinka',
    'System Information': 'Macluumaadka Nidaamka',
    'Dark Mode': 'Habka Madow',
    'Enable dark theme': 'Daar Habka Madow',
    'Notifications': 'Ogeysiis',
    'Enable push notifications': 'Daar Ogeysiisyada',
    'My Notifications': 'Ogeysiisyaday',
    'Send Message': 'Dir Farriin',
    'Send Message to Cashiers': 'Dir Farriin Caawiyayaal',
    'Title': 'Cinwaanka',
    'Message': 'Farriinta',
    'Select Cashiers': 'Dooro Caawiyayaal',
    'Send to all cashiers': 'Dir dhammaan caawiyayaal',
    'No cashiers found': 'Lama helin caawiyayaal',
    'Send Notification': 'Dir Ogeysiis',
    'Notification sent successfully': 'Ogeysiiska waa la diray si guul leh',
    'Mark all as read': 'Calaamadee dhammaan siday akhriyeen',
    'No notifications': 'Ogeysiis ma jiraan',
    'Mark as read': 'Calaamadee siday akhriyeen',
    'Priority': 'Muhiimadda',
    'Low': 'Hoos',
    'Medium': 'Dhexe',
    'High': 'Kor',
    'Urgent': 'Degdeg ah',
    'Info': 'Macluumaad',
    'Warning': 'Digniin',
    'Error': 'Khalad',
    'Success': 'Guul',
    'Language': 'Luuqad',
    'Currency': 'Lacag',
    'Update Profile': 'Cusboonaysii Xogta',
    'Login': 'Soo gal',
    'Logout': 'Ka bax',
    'Dashboard': 'Guddi',
    'POS': 'Iibinta',
    'Inventory': 'Kayd',
    'Reports': 'Warbixinno',
    'Add Product': 'Ku dar Alaab',
    'Product': 'Alaab',
    'Products': 'Alaabo',
    'Quantity': 'Tirada',
    'Price': 'Qiimaha',
    'Total': 'Wadarta',
    'Customer': 'Macmiil',
    'Sale': 'Iib',
    'Wholesale': 'Jumlo',
    'Retail': 'Tafaariiq',
    'Complete Sale': 'Dhameystir Iibka',
    'Cancel': 'Jooji',
    'Add': 'Ku dar',
    'Remove': 'Ka saar',
    'Search': 'Raadi',
    'Filter': 'Shaandhee',
    'Date': 'Taariikh',
    'Type': 'Nooc',
    'Profit': 'Faa\'iido',
    'Notes': 'Faallo',
    'Mode': 'Hab',
    'Payment Method': 'Habka Bixinta',
    'Order Summary': 'Wadarta Dalabka',
    'Checkout': 'Bixinta',
    'Cart is empty': 'Gaariga waa madhan yahay',
    'Add products to get started': 'Ku dar alaabo si aad u bilowdo',
    'Set Quantity': 'Deji Tirada',
    'Enter quantity': 'Geli tirada',
    'Set': 'Deji',
    'Clear Cart': 'Nadiifi Gaariga',
    'Shopping Cart': 'Gaariga Iibsiga',
    'Cost': 'Qiimaha',
    'Stock': 'Kayd',
    'LOW': 'YAR',
    'OUT': 'DHAMAADAY',
    'Sale completed successfully!': 'Iibku si guul leh ayuu u dhammaaday!',
    'Error processing sale': 'Khalad ayaa dhacay iibka',
    'Required, ≥': 'Lagu baahan yahay, ≥',
    'Must be ≥ cost × quantity': 'Waa in ay noqotaa ugu yaraan qiimaha × tirada',
    'Total entered amount must be at least the combined cost!': 'Wadarta la geliyay waa in ay ahaataa ugu yaraan wadarta qiimaha!',
    'Customer Name': 'Magaca Macmiilka',
    'Customer Phone': 'Telefoonka Macmiilka',
    'New Customer': 'Macmiil Cusub',
    'Cancel New Customer': 'Jooji Macmiilka Cusub',
    'New Customer Name': 'Magaca Macmiilka Cusub',
    'New Customer Phone': 'Telefoonka Macmiilka Cusub',
    'Enter new customer name': 'Geli magaca macmiilka cusub',
    'Enter phone (optional)': 'Geli telefoon (ikhtiyaari)',
    'Required for credit sales': 'Lagu baahan yahay iibka deynta',
    'Select or enter customer name': 'Dooro ama geli magaca macmiilka',
    'Complete your sale': 'Dhameystir iibkaaga',
    'Enter Custom Prices': 'Geli Qiimaha Gaarka ah',
    'Custom Price': 'Qiimo Gaar ah',
    'Enter custom price': 'Geli qiimo gaar ah',
    'Products Sold': 'Alaabo la iibiyay',
    'Unique Customers': 'Macmiil Gaar ah',
    'Cash in Hand': 'Lacag Gacanta ku jirta',
    'Total Orders': 'Wadarta Dalabka',
    'Total Sales': 'Wadarta Iibka',
    'Total Credits': 'Wadarta Deynta',
    'Cash (Balance Sheet)': 'Lacag (Xisaab)',
    'Payment Methods': 'Hababka Bixinta',
    'Product Transactions': 'Macluumaadka Alaabta',
    'No transactions found for this product.': 'Macluumaad lama helin alaabtan.',
    'Method': 'Habka',
    'Percentage': 'Boqolkiiba',
    'Total Amount': 'Wadarta Lacagta',
    'Sale ID': 'Lambarka Iibka',
    'Status': 'Xaalad',
    'Unit Price': 'Qiimaha Qaybta',
    'Total Price': 'Wadarta Qiimaha',
    'No payment method data': 'Xog looma helin habka bixinta',
    'Business Report': 'Warbixinta Ganacsiga',
    'Today': 'Maanta',
    'This Week': 'Toddobaadkan',
    'Last 7 Days': '7dii Maalmood ee la soo dhaafay',
    'Custom Range': 'Xilli Gaar ah',
    'All Time': 'Dhamaan Waqtiga',
    'All history': 'Dhammaan taariikhda',
    'No report data. Adjust filters and try again.': 'Xog warbixin lama helin. Fadlan shaandhee oo isku day mar kale.',
    'No recent transactions.': 'Macluumaad cusub lama helin.',
    'No transactions today.': 'Ma jiro wax macluumaad ah maanta.',
    'No transactions this week.': 'Ma jiro wax macluumaad ah toddobaadkan.',
    'No transactions for selected dates.': 'Ma jiro wax macluumaad ah taariikhaha la doortay.',
    'No products found': 'Alaabo lama helin',
    'Low Stock': 'Kayd Yaran',
    'In Stock': 'Kayd Jira',
    'Edit Product': 'Tafatir Alaab',
    'Delete Product': 'Tirtir Alaab',
    'Are you sure you want to delete this product?': 'Ma hubtaa inaad tirtirayso alaabtan?',
    'This action cannot be undone.': 'Falkan dib looma noqon karo.',
    'Add New Product': 'Ku dar Alaab Cusub',
    'Create a new product in your inventory': 'Ku dar alaab cusub kaydkaaga',
    'Update product information': 'Cusboonaysii xogta alaabta',
    'Product Name *': 'Magaca Alaabta *',
    'SKU *': 'SKU *',
    'Description': 'Sharaxaad',
    'Price *': 'Qiimaha *',
    'Cost *': 'Qiimaha *',
    'Stock Quantity': 'Tirada Kaydka',
    'Category': 'Qayb',
    'Add Image': 'Ku dar Sawir',
    'Add Product': 'Ku dar Alaab',
    'Update Product': 'Cusboonaysii Alaab',
    'orders': 'dalabyo',
    'avg': 'celcelis',
    'active': 'firfircoon',
    'low stock': 'kaydk yar',
    'Gross profit': 'Faa\'iido guud',
    'Available': 'La heli karo',
    'Receivables': 'Lacag la sugayo',
    'Credit Section': 'Qaybta Deynta',
    'Pay': 'Bixi',
    'Settled': 'La bixiyay',
    'Settled on': 'La bixiyay',
    'Payment Error': 'Khalad Bixinta',
    'OK': 'OK',
    'Unknown': 'Aan la garanayn',
    'Yesterday': 'Shalay',
    'days ago': 'maalmo kahor',
    'Credit Transactions for': 'Deynka Macmiilka',
    'No product details available': 'Faahfaahin alaab lama helin',
    'Payment History:': 'Taariikhda Bixinta:',
    'Close': 'Xidh',
    // --- Additional translations for POS and inventory ---
    'search_products': 'Raadi Alaab',
    'refresh_products': 'Cusboonaysii Alaab',
    'no_products_found': 'Alaabo lama helin',
    'select_sale_mode': 'Dooro Habka Iibka',
    'is_this_sale_retail_or_wholesale': 'Iibkan ma jumlo mise tafaariiq?',
    'retail': 'Tafaariiq',
    'wholesale': 'Jumlo',
    'wholesale_quantity': 'Tirada Jumlada',
    'quantity': 'Tirada',
    'enter_wholesale_quantity': 'Geli tirada jumlada',
    'cancel': 'Jooji',
    'add': 'Ku dar',
    'low': 'YAR',
    'out': 'DHAMAADAY',
    'cost': 'Qiimaha',
    'stock': 'Kayd',
    'shopping_cart': 'Gaariga Iibsiga',
    'clear_cart': 'Nadiifi Gaariga',
    'cart_is_empty': 'Gaariga waa madhan yahay',
    'add_products_to_get_started': 'Ku dar alaabo si aad u bilowdo',
    'set_quantity': 'Deji Tirada',
    'enter_quantity': 'Geli tirada',
    'set': 'Deji',
    'total': 'Wadarta',
    'checkout': 'Bixinta',
    'order_summary': 'Wadarta Dalabka',
    'enter_custom_prices': 'Geli Qiimaha Gaarka ah',
    'custom_price': 'Qiimo Gaar ah',
    'enter_custom_price': 'Geli qiimo gaar ah',
    'required_min_cost_quantity': 'Lagu baahan yahay, ≥',
    'must_be_min_cost_quantity': 'Waa in ay noqotaa ugu yaraan qiimaha × tirada',
    'payment_method': 'Habka Bixinta',
    'customer_name': 'Magaca Macmiilka',
    'customer_name_optional': 'Magaca Macmiilka (Ikhtiyaari)',
    'select_or_enter_customer_name': 'Dooro ama geli magaca macmiilka',
    'customer_phone': 'Telefoonka Macmiilka',
    'required_for_credit_sales': 'Lagu baahan yahay iibka deynta',
    'cancel_new_customer': 'Jooji Macmiilka Cusub',
    'new_customer': 'Macmiil Cusub',
    'new_customer_name': 'Magaca Macmiilka Cusub',
    'enter_new_customer_name': 'Geli magaca macmiilka cusub',
    'new_customer_phone': 'Telefoonka Macmiilka Cusub',
    'enter_phone_optional': 'Geli telefoon (ikhtiyaari)',
    'total_entered_amount_must_be_at_least_combined_cost': 'Wadarta la geliyay waa in ay ahaataa ugu yaraan wadarta qiimaha!',
    'complete_sale': 'Dhameystir Iibka',
    'sale_completed_successfully': 'Iibku si guul leh ayuu u dhammaaday!',
    'error_processing_sale': 'Khalad ayaa dhacay iibka',
    'error_loading_products': 'Khalad ayaa dhacay xilliga la rarayo alaabta',
    // --- Inventory Screen Specific ---
    'Inventory Management': 'Maareynta Kaydka',
    'Manage your product inventory efficiently': 'Si hufan u maamul kaydka alaabtaada',
    'Refresh Data': 'Cusboonaysii Xogta',
    'Filters': 'Shaandheyn',
    'Search Products': 'Raadi Alaab',
    'Inventory Report': 'Warbixinta Kaydka',
    'SKU': 'SKU',
    'Start Date': 'Taariikhda Bilowga',
    'End Date': 'Taariikhda Dhammaadka',
    'Stock Summary': 'Kooban Kayd',
    'Sold Qty': 'Tiro la Iibiyay',
    'Qty Remaining': 'Tiro Hadhay',
    'Revenue': 'Dakhli',
    'TOTAL': 'WADARTA',
    'No stock summary data': 'Xog kooban kayd lama helin',
    'No report data, adjust filters and try again': 'Xog warbixin lama helin, fadlan shaandhee oo isku day mar kale',
    'Recent Transactions': 'Macluumaadkii Ugu Dambeeyay',
    'No recent transactions': 'Macluumaad cusub lama helin',
    'Todays Transactions': 'Macluumaadka Maanta',
    'No transactions today': 'Ma jiro wax macluumaad ah maanta',
    'This Weeks Transactions': 'Macluumaadka Toddobaadkan',
    'No transactions this week': 'Ma jiro wax macluumaad ah toddobaadkan',
    'Filter Transactions by Date': 'Shaandhee Macluumaadka Taariikhda',
    'No transactions for selected dates': 'Ma jiro wax macluumaad ah taariikhaha la doortay',
    'Loading products...': 'Alaabo ayaa la rarayaa...',
    'This action cannot be undone': 'Falkan dib looma noqon karo',
    'Delete': 'Tirtir',
    'Product added successfully': 'Alaab si guul leh ayaa loo daray',
    'Failed to add product. Please try again.': 'Ku darista alaabta waa ay guuldareysatay. Fadlan isku day mar kale.',
    'Product updated successfully': 'Alaab si guul leh ayaa loo cusboonaysiiyay',
    'Failed to update product. Please try again.': 'Cusboonaysiinta alaabta waa ay guuldareysatay. Fadlan isku day mar kale.',
    'Product deleted successfully': 'Alaab si guul leh ayaa loo tirtiray',
    'Error deleting product: ': 'Khalad ayaa dhacay tirtirka alaabta:',
    'Failed to load recent transactions:': 'Khalad ayaa dhacay xilliga la rarayo macluumaadkii ugu dambeeyay:',
    'Failed to load today\'s transactions:': 'Khalad ayaa dhacay xilliga la rarayo macluumaadka maanta:',
    'Failed to load this week\'s transactions:': 'Khalad ayaa dhacay xilliga la rarayo macluumaadka toddobaadkan:',
    'Failed to load filtered transactions:': 'Khalad ayaa dhacay xilliga la rarayo macluumaadka la shaandheeyay:',
    'Error loading data:': 'Khalad ayaa dhacay xilliga la rarayo xogta:',
    'Failed to load inventory report:': 'Khalad ayaa dhacay xilliga la rarayo warbixinta kaydka:',
    'Failed to load value report:': 'Khalad ayaa dhacay xilliga la rarayo warbixinta qiimaha:',
    // --- Reports Screen Specific ---
    'error': 'Khalad',
    'payment_methods': 'Hababka Bixinta',
    'no_payment_method_data': 'Xog looma helin habka bixinta',
    'product_transactions': 'Macluumaadka Alaabta',
    'no_transactions_found_for_product': 'Macluumaad lama helin alaabtan.',
    'custom_range_label': 'Xilli Gaar ah',
    'filter_by_date_title': 'Shaandhee Taariikhda',
    'all_time': 'Dhamaan Waqtiga',
    'today': 'Maanta',
    'this_week': 'Toddobaadkan',
    'last_7_days': '7dii Maalmood ee la soo dhaafay',
    'custom_range': 'Xilli Gaar ah',
    'filter_by_date_tooltip': 'Shaandhee taariikhda',
    'business_report_title': 'Warbixinta Ganacsiga',
    'items': 'alaabo',
    'total_amount': 'Wadarta Lacagta',
    // --- Settings Screen Translations ---
    'Username': 'Magaca Isticmaalaha',
    'Email': 'Iimaylka',
    'Current Password': 'Furaha Hadda',
    'New Password': 'Furaha Cusub',
    'Confirm Password': 'Xaqiiji Furaha',
    'Change Password': 'Beddel Furaha',
    'Select Language': 'Dooro Luuqad',
    'Select Currency': 'Dooro Lacag',
    'Profile updated successfully!': 'Xogta si guul leh ayaa loo cusboonaysiiyay!',
    'Failed to update profile: ': 'Cusboonaysiinta xogta waa ay guuldareysatay: ',
    'Backend Status': 'Xaaladda Backend',
    'Database Status': 'Xaaladda Database',
    'Total Products': 'Wadarta Alaabta',
    'Total Customers': 'Wadarta Macmiilka',
    'Total Sales': 'Wadarta Iibka',
    'Database Size': 'Cabbirka Database',
    'Manage Cashiers': 'Maamul Caawiyayaal',
    'Create and manage cashier accounts for your business': 'Abuur oo maamul xisaabta caawiyayaal ganacsigaaga',
    'Connection Details': 'Faahfaahinta Xiriirka',
    'Backend: ': 'Backend: ',
    'Database: ': 'Database: ',
    'Last Check: ': 'Hubinta ugu Dambeysay: ',
    'Connected': 'La xirto',
    'Disconnected': 'La xirtay',
    // --- Admin and Cashier Management ---
    'Failed to save cashier: ': 'Ku kaydinta caawiyaha waa ay guuldareysatay: ',
    'Reset Password for ': 'Dib u deji furaha ',
    'Password reset': 'Furaha waa la dib u dejiyay',
    'Failed to reset password: ': 'Dib u dejinta furaha waa ay guuldareysatay: ',
    'Reset': 'Dib u deji',
    'Failed to deactivate cashier: ': 'Xayirka caawiyaha waa ay guuldareysatay: ',
    'Failed to activate cashier: ': 'Firfircoonka caawiyaha waa ay guuldareysatay: ',
    'You do not have permission to manage cashiers': 'Ma lihid oggolaansho maamulka caawiyayaal',
    'Current role: ': 'Jagada hadda: ',
    'Business ID: ': 'Lambarka Ganacsiga: ',
    'No cashiers found': 'Caawiyayaal lama helin',
    'Add your first cashier to get started': 'Ku dar caawiyahaaga ugu horreeya si aad u bilowdo',
    'Edit': 'Tafatir',
    'Reset Password': 'Dib u deji Furaha',
    'Deactivate': 'Xayir',
    'Activate': 'Firfircoon ka dhig',
    // --- Dashboard Screen ---
    'Error loading dashboard: ': 'Khalad ayaa dhacay xilliga la rarayo guddiga: ',
    'Loading transactions...': 'Macluumaad ayaa la rarayaa...',
    'Paid:   \$': 'La bixiyay:   \$',
    'Remaining: \$': 'Hadhay: \$',
    'Payment History:': 'Taariikhda Bixinta:',
    'Amount owed: \$': 'Lacagta la sugayo: \$',
    'Payment recorded. Remaining: \$': 'Bixin waa la diiwaangeliyay. Hadhay: \$',
    'Settled on: ': 'La bixiyay: ',
    'Phone': 'Telefoon',
    'Credit Sales': 'Iibka Deynta',
    'Total Credit': 'Wadarta Deynta',
    'Actions': 'Falalka',
    // --- Damaged Products Screen ---
    'Damaged Products': 'Alaabo la Xasuuqay',
    'No damaged products found': 'Alaabo la xasuuqay lama helin',
    'Qty: ': 'Tiro: ',
    'Date: ': 'Taariikh: ',
    'Reason: ': 'Sababta: ',
    'Loss: \$': 'Khasaaraha: \$',
    'Reported by: ': 'Waxaa sheegay: ',
    'Select filters and load report': 'Dooro shaandheyn oo soo deji warbixin',
    'Report Filters': 'Shaandheynka Warbixinta',
    'All Types': 'Dhammaan Noocyada',
    'Load Report': 'Soo deji Warbixin',
    'Damage Type Breakdown': 'Qaybinta Noocyada Khasaaraha',
    ' incidents, ': ' dhacdo, ',
    ' items': ' alaabo',
    'Top Damaged Products': 'Alaabta Ugu Khasaaraha Badan',
    'Cashier Breakdown': 'Qaybinta Caawiyayaal',
    'Detailed Damaged Products': 'Alaabta la Xasuuqay ee Faahfaahsan',
    'Delete Damaged Product': 'Tirtir Alaabta la Xasuuqay',
    'Are you sure you want to delete this damaged product record? This will restore the quantity to stock.': 'Ma hubtaa inaad tirtirayso xogta alaabta la xasuuqay? Tani waxay dib u soo celin doontaa tirada kaydka.',
    'Damaged product deleted successfully': 'Alaabta la xasuuqay si guul leh ayaa loo tirtiray',
    'Please select a product': 'Fadlan dooro alaab',
    'Damaged product reported successfully': 'Alaabta la xasuuqay si guul leh ayaa la sheegay',
    'Failed to report damaged product: ': 'Sheegida alaabta la xasuuqay waa ay guuldareysatay: ',
    'Report Damaged Product': 'Sheeg Alaabta la Xasuuqay',
    ' - Stock: ': ' - Kayd: ',
    'Damaged product updated successfully': 'Alaabta la xasuuqay si guul leh ayaa loo cusboonaysiiyay',
    'Failed to update damaged product: ': 'Cusboonaysiinta alaabta la xasuuqay waa ay guuldareysatay: ',
    'Edit Damaged Product': 'Tafatir Alaabta la Xasuuqay',
    'Product: ': 'Alaab: ',
    'Update': 'Cusboonaysii',
    'unread notifications': 'ogeysiis aan la akhrin',
    // --- Superadmin Dashboard Translations ---
    'Superadmin Dashboard': 'Guddi Maamulaha Sare',
    'System': 'Nidaamka',
    'Businesses': 'Ganacsiga',
    'Billing': 'Bixinta',
    'Backups': 'Kaydinta',
    'Data': 'Xogta',
    'Users': 'Isticmaalaha',
    'Settings': 'Dejinta',
    'Notifications': 'Ogeysiis',
    'Audit': 'Hubinta',
    'Analytics': 'Falanqaynta',
    'Business Analytics': 'Falanqaynta Ganacsiga',
    'Deleted Data': 'Xogta la Tirtiray',
    'Error: ': 'Khalad: ',
    'unknown': 'aan la garanayn',
    'System Health': 'Caafimaadka Nidaamka',
    'Active Sessions': 'Furaha Firfircoon',
    'Recent Errors': 'Khaladaadka Ugu Dambeeyay',
    'Performance Metrics': 'Talaabooyinka Waxqabadka',
    'Status: ': 'Xaalad: ',
    'Uptime: ': 'Waqtiga Shaqada: ',
    'Node.js: ': 'Node.js: ',
    'Platform: ': 'Platform: ',
    'CPU Usage: ': 'Isticmaalka CPU: ',
    'Memory Usage: ': 'Isticmaalka Xusuusta: ',
    'Active DB Connections: ': 'Xiriirrada Database Firfircoon: ',
    'Errors:': 'Khaladaad:',
    'No active sessions.': 'Furo firfircoon ma jiraan.',
    'Last login: ': 'Galitaanka ugu dambeeyay: ',
    'No recent errors.': 'Khalad cusub ma jiraan.',
    'Database Queries: ': 'Su\'aalaha Database: ',
    'Avg. Response Time: ': 'Celceliska Jawaabta: ',
    'Last Query: ': 'Su\'aasha ugu dambeysay: ',
    'Active Users (last 7 days): ': 'Isticmaalaha Firfircoon (7dii maalmood ee ugu dambeeyay): ',
    'System CPU Usage: ': 'Isticmaalka CPU Nidaamka: ',
    'System Memory Usage: ': 'Isticmaalka Xusuusta Nidaamka: ',
    'Node Uptime: ': 'Waqtiga Shaqada Node: ',
    'Business Management': 'Maareynta Ganacsiga',
    'Add Business': 'Ku dar Ganacsi',
    'Page ': 'Bogga ',
    ' of ': ' ka mid ah ',
    'Send Message': 'Dir Farriin',
    'Add Payment': 'Ku dar Bixin',
    'Manage Users': 'Maamul Isticmaalaha',
    'Toggle Status': 'Beddel Xaalad',
    'Create New Business': 'Abuur Ganacsi Cusub',
    'Business Information': 'Macluumaadka Ganacsiga',
    'Business Admin Account': 'Xisaabta Maamulaha Ganacsiga',
    'Business created successfully': 'Ganacsi si guul leh ayaa loo abuuray',
    'Error creating business: ': 'Khalad ayaa dhacay abuurka ganacsiga: ',
    'Create': 'Abuur',
    ' - Users': ' - Isticmaalaha',
    'Error loading users: ': 'Khalad ayaa dhacay xilliga la rarayo isticmaalaha: ',
    'Select Business': 'Dooro Ganacsi',
    'Error loading businesses': 'Khalad ayaa dhacay xilliga la rarayo ganacsiga',
    'No businesses available': 'Ganacsi ma jiraan',
    'No data available': 'Xog ma jiraan',
    'Send Message to ': 'Dir Farriin ',
    'Please fill all required fields': 'Fadlan buuxi dhammaan meelaha loo baahan yahay',
    'Message sent successfully': 'Farriinta si guul leh ayaa la diray',
    'Error sending message: ': 'Khalad ayaa dhacay dirista farriinta: ',
    'Add Payment for ': 'Ku dar Bixin ',
    'Payment added successfully': 'Bixin si guul leh ayaa loo daray',
    'Error adding payment: ': 'Khalad ayaa dhacay ku darista bixinta: ',
    'Business Settings - ': 'Dejinta Ganacsiga - ',
    'Business settings updated successfully': 'Dejinta ganacsiga si guul leh ayaa loo cusboonaysiiyay',
    'Error updating settings: ': 'Khalad ayaa dhacay cusboonaysiinta dejinta: ',
    'Are you sure you want to ': 'Ma hubtaa inaad rabto inaad ',
    'suspend': 'xayirto',
    'activate': 'firfircoon ka dhigto',
    ' suspended': ' si xayiran ayaa loo xayiray',
    ' activated': ' si firfircoon ayaa loo sameeyay',
    ' successfully': ' si guul leh',
    'Error updating status: ': 'Khalad ayaa dhacay cusboonaysiinta xaaladda: ',
    'Export Report': 'Soo saar Warbixin',
    'Generate Monthly Bill': 'Samee Billka Bishii',
    'Subscription Plan: ': 'Qorshaha Subscription: ',
    'Monthly Fee: \$': 'Lacagta Bishii: \$',
    'Max Users: ': 'Isticmaalaha Ugu Badan: ',
    'Max Products: ': 'Alaabta Ugu Badan: ',
    'User Overage Fee: \$': 'Lacagta Isticmaalaha Dheeraadka: \$',
    '/user': '/isticmaale',
    'Product Overage Fee: \$': 'Lacagta Alaabta Dheeraadka: \$',
    '/product': '/alaab',
    // --- Additional missing translations for inventory screen ---
    'Error loading data: ': 'Khalad ayaa dhacay xilliga la rarayo xogta: ',
    'Error loading inventory report: ': 'Khalad ayaa dhacay xilliga la rarayo warbixinta kaydka: ',
    'Transactions for ': 'Macluumaad ',
    'No transactions found.': 'Macluumaad lama helin.',
    'Qty': 'Tiro',
    'Sale Amount': 'Lacagta Iibka',
    'Cashier': 'Caawiyaha',
    'Stock Summary': 'Kooban Kayd',
    'Recent Transactions': 'Macluumaadkii Ugu Dambeeyay',
    'Todays Transactions': 'Macluumaadka Maanta',
    'This Weeks Transactions': 'Macluumaadka Toddobaadkan',
    'Filter Transactions by Date': 'Shaandhee Macluumaadka Taariikhda',
    'Product added successfully': 'Alaab si guul leh ayaa loo daray',
    'Failed to add product. Please try again.': 'Ku darista alaabta waa ay guuldareysatay. Fadlan isku day mar kale.',
    'Product updated successfully': 'Alaab si guul leh ayaa loo cusboonaysiiyay',
    'Failed to update product. Please try again.': 'Cusboonaysiinta alaabta waa ay guuldareysatay. Fadlan isku day mar kale.',
    'Product deleted successfully': 'Alaab si guul leh ayaa loo tirtiray',
    'Error deleting product: ': 'Khalad ayaa dhacay tirtirka alaabta: ',
    'Error picking image: ': 'Khalad ayaa dhacay doorashada sawirka: ',
    // --- Additional missing translations for inventory screen ---
    'Transactions for ': 'Macluumaad ',
    'No transactions found.': 'Macluumaad lama helin.',
    'Date': 'Taariikh',
    'Type': 'Nooc',
    'Qty': 'Tiro',
    'Sale Amount': 'Lacagta Iibka',
    'Profit': 'Faa\'iido',
    'Notes': 'Faallo',
    'Mode': 'Hab',
    'Cashier': 'Caawiyaha',
    'Low Stock': 'Kayd Yaran',
    'Stock Summary': 'Kooban Kayd',
    'Product': 'Alaab',
    'SKU': 'SKU',
    'Category': 'Qayb',
    'Sold Qty': 'Tiro la Iibiyay',
    'Qty Remaining': 'Tiro Hadhay',
    'Revenue': 'Dakhli',
    'Recent Transactions': 'Macluumaadkii Ugu Dambeeyay',
    'Todays Transactions': 'Macluumaadka Maanta',
    'This Weeks Transactions': 'Macluumaadka Toddobaadkan',
    'Filter Transactions by Date': 'Shaandhee Macluumaadka Taariikhda',
    'Product added successfully': 'Alaab si guul leh ayaa loo daray',
    'Failed to add product. Please try again.': 'Ku darista alaabta waa ay guuldareysatay. Fadlan isku day mar kale.',
    'Product updated successfully': 'Alaab si guul leh ayaa loo cusboonaysiiyay',
    'Failed to update product. Please try again.': 'Cusboonaysiinta alaabta waa ay guuldareysatay. Fadlan isku day mar kale.',
    'Product deleted successfully': 'Alaab si guul leh ayaa loo tirtiray',
    'Error deleting product: ': 'Khalad ayaa dhacay tirtirka alaabta: ',
    'Error: ': 'Khalad: ',
    // --- Additional missing translations for reports screen ---
    'Filter by Cashier: ': 'Shaandhee Caawiyaha: ',
    'All Cashiers': 'Dhammaan Caawiyayaal',
    'Cashier': 'Caawiyaha',
    // --- Additional missing translations for home screen ---
    'Profile': 'Xogta',
    // --- Navigation labels ---
    'Dashboard': 'Guddi',
    'POS': 'Iibinta',
    'Inventory': 'Kayd',
    'Damaged': 'Xasuuqay',
    'Reports': 'Warbixinno',
    'Settings': 'Dejinta',
    'Accounting': 'Xisaab',
    // --- Accounting translations ---
    'Failed to load accounting dashboard: ': 'Khalad ayaa dhacay xilliga la rarayo guddiga xisaabta: ',
    'Inflow': 'Dakhli',
    'Outflow': 'Dakhlaad',
    'Total Income': 'Wadarta Dakhliga',
    'Total Expenses': 'Wadarta Kharaajka',
    'Net Profit': 'Faa\'iido Saf ah',
    'Cash': 'Lacag',
    'Receivables': 'Lacag la Sugayo',
    'Liabilities': 'Deynta',
    'Accounting Dashboard': 'Guddi Xisaabta',
    'Cash Flow': 'Dakhlaadka Lacagta',
    'No data': 'Xog ma jiraan',
    // --- Expenses translations ---
    'Failed to load expenses: ': 'Khalad ayaa dhacay xilliga la rarayo kharaajka: ',
    'Cancel': 'Jooji',
    'Failed to save expense: ': 'Ku kaydinta kharaajka waa ay guuldareysatay: ',
    'Delete Expense': 'Tirtir Kharaaj',
    'Are you sure you want to delete this expense?': 'Ma hubtaa inaad tirtirayso kharaajkan?',
    'Failed to delete expense: ': 'Tirtirka kharaajka waa ay guuldareysatay: ',
    'Delete': 'Tirtir',
    'Category': 'Qayb',
    // --- User Management Translations ---
    'Create New User': 'Abuur Isticmaale Cusub',
    'Username': 'Magaca Isticmaalaha',
    'Enter username (3-20 characters)': 'Geli magaca isticmaalaha (3-20 xaraf)',
    'Username must be 3-20 characters long': 'Magaca isticmaalaha waa inuu ahaadaa 3-20 xaraf',
    'Email': 'Iimaylka',
    'Enter email address': 'Geli cinwaanka iimaylka',
    'Password': 'Furaha',
    'Enter password (min 6 characters)': 'Geli furaha (ugu yaraan 6 xaraf)',
    'Password must be at least 6 characters': 'Furaha waa inay ahaadaan ugu yaraan 6 xaraf',
    'Confirm Password': 'Xaqiiji Furaha',
    'Confirm your password': 'Xaqiiji furahaga',
    'Passwords do not match': 'Furaha ma isku mid aha',
    'Role': 'Jagada',
    'SUPERADMIN': 'MAAMULAAHA SARE',
    'ADMIN': 'MAAMULAAHA',
    'MANAGER': 'MAAMULAAHA',
    'CASHIER': 'CAAWIYAAHA',
    'Cancel': 'Jooji',
    'Create': 'Abuur',
    'All fields are required': 'Dhammaan meelaha ayaa loo baahan yahay',
    'User created successfully': 'Isticmaale si guul leh ayaa loo abuuray',
    'Error creating user': 'Khalad ayaa dhacay abuurka isticmaalaha',
    'Username already exists': 'Magaca isticmaalaha waa la isticmaalaa',
    'Email already exists': 'Iimaylka waa la isticmaalaa',
    'Edit Cashier': 'Tafatir Caawiyaha',
    'Add Cashier': 'Ku dar Caawiyaha',
    'Username and email are required': 'Magaca isticmaalaha iyo iimaylka ayaa loo baahan yahay',
    'Password is required': 'Furaha ayaa loo baahan yahay',
    'Cashier updated successfully': 'Caawiyaha si guul leh ayaa loo cusboonaysiiyay',
    'Cashier created successfully': 'Caawiyaha si guul leh ayaa loo abuuray',
    'Save': 'Kaydi',
    'Add': 'Ku dar',
    'All': 'Dhammaan',
    'Vendor': 'Alaab bixiyaha',
    'Clear Filters': 'Nadiifi Shaandheyn',
    'Expenses': 'Kharaaj',
    'No expenses found.': 'Kharaaj lama helin.',
    'Edit Expense': 'Tafatir Kharaaj',
    'Add Expense': 'Ku dar Kharaaj',
    'Date': 'Taariikh',
    'Amount': 'Lacagta',
    'Notes': 'Faallo',
    'Date required': 'Taariikh ayaa loo baahan yahay',
    'Amount required': 'Lacagta ayaa loo baahan yahay',
    'Category required': 'Qaybta ayaa loo baahan yahay',
    // --- Cash Flow translations ---
    'Failed to load cash flows: ': 'Khalad ayaa dhacay xilliga la rarayo dakhlaadka lacagta: ',
    'Add Cash Flow': 'Ku dar Dakhlaadka Lacagta',
    'Inflow': 'Dakhli',
    'Outflow': 'Dakhlaad',
    'Failed to add cash flow: ': 'Ku darista dakhlaadka lacagta waa ay guuldareysatay: ',
    'Add': 'Ku dar',
    'Cash Flow': 'Dakhlaadka Lacagta',
    'No cash flow records found.': 'Dakhlaad lacag lama helin.',
    // --- Payables translations ---
    'Failed to load payables: ': 'Khalad ayaa dhacay xilliga la rarayo deynta: ',
    'Unpaid': 'Aan la bixin',
    'Paid': 'La bixiyay',
    'Overdue': 'Ka dhaafay mudada',
    'Failed to save payable: ': 'Ku kaydinta deynta waa ay guuldareysatay: ',
    'Delete Payable': 'Tirtir Deyn',
    'Are you sure you want to delete this payable?': 'Ma hubtaa inaad tirtirayso deyntan?',
    'Failed to delete payable: ': 'Tirtirka deynta waa ay guuldareysatay: ',
    'Accounts Payable': 'Deynta Xisaabta',
    'No payables found.': 'Deyn lama helin.',
    'Due: ': 'Mudada: ',
    'Status: ': 'Xaalad: ',
    // --- Vendors translations ---
    'Vendors': 'Alaab Bixiyayaal',
    'Vendors management will be here.': 'Maareynta alaab bixiyayaal waxay halkan ku jiri doontaa.',
    // --- Admin Dashboard Translations ---
    'General': 'Guud',
    'Damages': 'Xasuuq',
    'Credit Management': 'Maareynta Deynta',
    'Toggle Credit Section': 'Beddel Qaybta Deynta',
    'Credit Sales': 'Iibka Deynta',
    'Outstanding': 'Hadhay',
    'View Details': 'Eeg Faahfaahin',
    'Please enter a valid payment amount': 'Fadlan geli lacag bixin oo sax ah',
    'Payment amount cannot exceed outstanding amount': 'Lacagta bixinta ma noqon karto ka weyn lacagta hadhay',
    'No phone': 'Telefoon ma jiraan',
    'No email': 'Iimayl ma jiraan',
    'sales': 'iib',
    // --- Accounting Translations ---
    'General Ledger': 'Xisaab Guud',
    'Total Income': 'Wadarta Dakhliga',
    'Total Expenses': 'Wadarta Kharaajka',
    'Net Profit': 'Faa\'iido Saf ah',
    'Cash': 'Lacag',
    'Receivables': 'Lacag la Sugayo',
    'Liabilities': 'Deynta',
    'Inflow': 'Dakhli',
    'Outflow': 'Dakhlaad',
    // --- Damaged Products Translations ---
    'Damage Type': 'Nooca Xasuuqa',
    // --- Reports Screen Translations ---
    'Filter by Date': 'Shaandhee Taariikhda',
    'Filter by Cashier': 'Shaandhee Caawiyaha',
    'Business Report': 'Warbixinta Ganacsiga',
    'Sales Report': 'Warbixinta Iibka',
    'Balance Sheet': 'Waraaqa Xisaabta',
    'Damaged Products Report': 'Warbixinta Alaabta la Xasuuqay',
    'Product Transactions': 'Macluumaadka Alaabta',
    'No transactions found for this product': 'Macluumaad lama helin alaabtan',
    // --- Inventory Screen Translations ---
    'Filters': 'Shaandheyn',
    'Search Products': 'Raadi Alaab',
    'Inventory Report': 'Warbixinta Kaydka',
    'Todays Transactions': 'Macluumaadka Maanta',
    'This Weeks Transactions': 'Macluumaadka Toddobaadkan',
    'Filter Transactions by Date': 'Shaandhee Macluumaadka Taariikhda',
    'No transactions for selected dates': 'Ma jiro wax macluumaad ah taariikhaha la doortay',
    'No recent transactions': 'Macluumaad cusub lama helin',
    'No transactions today': 'Ma jiro wax macluumaad ah maanta',
    'No transactions this week': 'Ma jiro wax macluumaad ah toddobaadkan',
    'No stock summary data': 'Xog kooban kayd lama helin',
    'No report data, adjust filters and try again': 'Xog warbixin lama helin, fadlan shaandhee oo isku day mar kale',
    'Loading products...': 'Alaabo ayaa la rarayaa...',
    // --- Dashboard Screen Translations ---
    'Monitor your business performance': 'Dareerka ganacsigaaga',
    'Recent Sales': 'Iibka Cusub',
    'Low Stock Alert': 'Digniin Kayd Yaran',
    'Total Profit': 'Wadarta Faa\'iido',
    'Average Order Value': 'Qiimaha Celceliska Dalabka',
    'Low Stock Count': 'Tiro Kayd Yaran',
    'Cash on Hand': 'Lacag La Heli Karo',
    // --- POS Screen Translations ---
    'Uncategorized': 'Aan la Qaybin',
    'Search Products': 'Raadi Alaab',
    'Select Category': 'Dooro Qayb',
    'Add to Cart': 'Ku dar Gaariga',
    'Remove from Cart': 'Ka saar Gaariga',
    'Set Quantity': 'Deji Tirada',
    'Enter quantity': 'Geli tirada',
    'Clear Cart': 'Nadiifi Gaariga',
    'Order Summary': 'Wadarta Dalabka',
    'Payment Method': 'Habka Bixinta',
    'Customer Name': 'Magaca Macmiilka',
    'Customer Phone': 'Telefoonka Macmiilka',
    'New Customer': 'Macmiil Cusub',
    'Complete Sale': 'Dhameystir Iibka',
    'Remove': 'Ka saar',
    'Search': 'Raadi',
    'Filter': 'Shaandhee',
    'Error loading dashboard data': 'Khalad ayaa dhacay xilliga la rarayo xogta guddiga',
    // --- POS Additional Translations ---
    'Point of Sale': 'Iibka Alaabta',
    'Sale Mode': 'Habka Iibka',
    'Wholesale Quantity': 'Tirada Jumlada',
    'Enter Wholesale Quantity': 'Geli Tirada Jumlada',
    // --- Outstanding Credit Translations ---
    'Total Outstanding': 'Wadarta Hadhay',
    'Outstanding Amount': 'Lacagta Hadhay',
    'Credit Customers': 'Macmiilka Deynta',
    'No credit customers found.': 'Macmiil deyn lama helin.',
  },
};

String t(BuildContext context, String key) {
  final lang = Provider.of<SettingsProvider>(context, listen: false).language;
  return translations[lang]?[key] ?? key;
} 